import { participants, type Participant } from './canton-data';

// ── Interfaces ──────────────────────────────────────────

export interface IntelEvent {
  id: string;
  name: string;
  type: 'Conference' | 'Summit' | 'Working Group' | 'Industry Day' | 'Hackathon' | 'Roadshow';
  startDate: string;
  endDate: string;
  location: string;
  venue?: string;
  attendeeCap?: number;
  applicationRequired: boolean;
  cantonRelevance: 'High' | 'Medium' | 'Low';
  cantonSpeakerIds: string[];
  cantonOrgIds: string[];
  topicsCovered: string[];
  sourceUrl?: string;
  notes?: string;
  flowrydAttended: boolean;
  flowrydSpeaking: boolean;
  followUpActions?: string;
  lat?: number;
  lng?: number;
}

export interface IntelPerson {
  id: string;
  fullName: string;
  currentRole: string;
  organizationId: string;
  organization: string;
  cantonRoles: string[];
  linkedinUrl?: string;
  twitterHandle?: string;
  eventIds: string[];
  mediaIds: string[];
  relationshipToFlowryd: 'None' | 'Warm' | 'Connected' | 'Partner' | 'Prospect' | 'Self' | 'N/A';
  introducedById?: string;
  lastContactDate?: string;
  notes?: string;
  priority: 'High' | 'Medium' | 'Low' | 'Critical' | 'N/A';
}

export interface IntelMedia {
  id: string;
  title: string;
  mediaType: 'Podcast' | 'Interview' | 'Webinar' | 'Article' | 'Research Report' | 'Video';
  publisher: string;
  seriesName?: string;
  publicationDate: string;
  durationMinutes?: number;
  cantonSpeakerIds: string[];
  cantonOrgIds: string[];
  topicsCovered: string[];
  keyQuotes?: string;
  cantonMentions: boolean;
  sentiment: 'Bullish' | 'Neutral' | 'Bearish';
  sourceUrl?: string;
  transcriptAvailable: boolean;
  strategicInsights?: string;
}

export interface IntelAnnouncement {
  id: string;
  date: string;
  participants: string[];
  type: string;
  description: string;
  sourceUrl?: string;
  impact: 'Critical' | 'High' | 'Medium' | 'Low';
  notes?: string;
}

export interface CIPRecord {
  cipNumber: string;
  title: string;
  proposer: string;
  type: string;
  svWeightRequested?: number;
  status: string;
  voteResult?: string;
  svNodeopsVote?: string;
  ccDistributed?: number;
  description?: string;
  notes?: string;
}

// ── Data ────────────────────────────────────────────────

export const intelEvents: IntelEvent[] = [
  {
    id: 'evt-2026-001',
    name: 'CfC St. Moritz 2026',
    type: 'Conference' as const,
    startDate: '2026-01-14T09:00:00Z',
    endDate: '2026-01-16T18:00:00Z',
    location: 'St. Moritz, Switzerland',
    attendeeCap: 250,
    applicationRequired: true,
    cantonRelevance: 'High' as const,
    cantonSpeakerIds: ['Don Wilson', 'Yuval Rooz', 'Jenny Johnson', 'Talia Klein', 'Ambre Soubiran', 'Anton Katz', 'Fernando Vázquez Cao'],
    cantonOrgIds: ['p_drw', 'p_digitalasset', 'p_franklintempleton', 'p_dtcc', 'p_kaiko', 'p_talos', 'p_chainlink'],
    topicsCovered: ['Tokenization', 'Regulation', 'ETFs', 'Institutional Adoption'],
    flowrydAttended: false,
    flowrydSpeaking: false,
    followUpActions: 'Apply CfC 2027 Oct 2026; Target Kaiko + Talos',
    notes: 'Pre-Davos; 8 Canton orgs; invite-only 250 cap',
  }
];

export const intelPeople: IntelPerson[] = [
  {
    id: 'per-001',
    fullName: 'Don Wilson',
    currentRole: 'Founder',
    organizationId: 'p_drw',
    organization: 'DRW',
    cantonRoles: ['Investor', 'Board'],
    eventIds: ['evt-2026_001'],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: '$206M CC; Controls Cumberland; DA Board Co-leads Woodside AI venture studio with Suna Said and Edward Hu. CIP-0059 (Weight 10). Working with Blackstone on Private Credit + Fund Admin for Canton.',
  },
  {
    id: 'per-002',
    fullName: 'Yuval Rooz',
    currentRole: 'CEO',
    organizationId: 'p_digitalasset',
    organization: 'Digital Asset',
    cantonRoles: ['Founder', 'SV'],
    eventIds: ['evt-2026_001'],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'Canton creator',
  },
  {
    id: 'per-003',
    fullName: 'Jenny Johnson',
    currentRole: 'CEO',
    organizationId: 'p_franklintempleton',
    organization: 'Franklin Templeton',
    cantonRoles: ['Investor'],
    eventIds: ['evt-2026_001'],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'Benji tokenized fund',
  },
  {
    id: 'per-004',
    fullName: 'Talia Klein',
    currentRole: '',
    organizationId: 'p_dtcc',
    organization: 'DTCC',
    cantonRoles: ['SV'],
    eventIds: ['evt-2026_001'],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
  },
  {
    id: 'per-005',
    fullName: 'Ambre Soubiran',
    currentRole: 'CEO',
    organizationId: 'p_kaiko',
    organization: 'Kaiko',
    cantonRoles: ['SV', 'FA'],
    eventIds: ['evt-2026_001'],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'CIP-0063 Weight 6.5',
  },
  {
    id: 'per-006',
    fullName: 'Anton Katz',
    currentRole: 'CEO',
    organizationId: 'p_talos',
    organization: 'Talos',
    cantonRoles: ['SV'],
    eventIds: ['evt-2026_001'],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'CIP-0085 Weight 6.5',
  },
  {
    id: 'per-007',
    fullName: 'Fernando Vázquez Cao',
    currentRole: '',
    organizationId: 'p_chainlink',
    organization: 'Chainlink',
    cantonRoles: ['SV'],
    eventIds: ['evt-2026_001'],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Low' as const,
    notes: 'CIP-0061 Weight 7.5',
  },
  {
    id: 'per-008',
    fullName: 'Catherine',
    currentRole: '',
    organizationId: 'p_communifyfincentric',
    organization: 'Communify Fincentric',
    cantonRoles: ['Prospect'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'Prospect' as const,
    priority: 'High' as const,
    lastContactDate: '2026-01-29',
    notes: 'CF partnership for SV CIP',
  },
  {
    id: 'per-009',
    fullName: 'Veronica',
    currentRole: '',
    organizationId: 'p_7ridgec7',
    organization: '7RIDGE C7',
    cantonRoles: ['SV'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'Partner' as const,
    priority: 'High' as const,
    notes: 'Flowryd SV sponsor candidate',
  },
  {
    id: 'per-010',
    fullName: 'Pinar',
    currentRole: '',
    organizationId: 'p_7ridgec7',
    organization: '7RIDGE C7',
    cantonRoles: ['SV'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'Partner' as const,
    priority: 'High' as const,
    notes: 'Flowryd SV sponsor candidate',
  },
  {
    id: 'per-011',
    fullName: 'Liz Towler',
    currentRole: 'Founder & CEO',
    organizationId: 'p_flowryd',
    organization: 'Flowryd',
    cantonRoles: ['FA', 'Validator'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'Self' as const,
    priority: 'N/A' as const,
    notes: 'Flowryd founder',
  },
  {
    id: 'per-012',
    fullName: 'Suna Said',
    currentRole: '',
    organizationId: 'p_woodsideai',
    organization: 'Woodside AI',
    cantonRoles: ['SV'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Low' as const,
    notes: 'Don Wilson vehicle; CIP-0059 Weight 10',
  },
  {
    id: 'per-013',
    fullName: 'Tony McLaughlin',
    currentRole: '',
    organizationId: 'p_ubyx',
    organization: 'Ubyx',
    cantonRoles: ['SV'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Low' as const,
    notes: 'CIP-0071 Weight 5',
  },
  {
    id: 'per-014',
    fullName: 'Suleyman Onay',
    currentRole: 'Managing Director, Colendi',
    organizationId: 'p_bosphorussv',
    organization: 'Bosphorus SV',
    cantonRoles: ['SV Operator'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'CIP-0093 lead. $100M+ equity raised. Ex-BCG. Harvard MBA. SETL acquisition. Circle CPN partnership. Turkiye/GCC/Central Asia focus.',
  },
  {
    id: 'per-015',
    fullName: 'Ilker Zorluoglu',
    currentRole: 'Operator/Strategist',
    organizationId: 'p_bosphorussv',
    organization: 'Bosphorus SV',
    cantonRoles: ['SV Operator'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Low' as const,
    notes: 'Ex-Outlier Ventures MENA head. ETH Global Ambassador. Industrial Engineering, Bilkent. Political campaign strategist in Turkiye.',
  },
  {
    id: 'per-016',
    fullName: 'Ari Nazir',
    currentRole: 'Operator',
    organizationId: 'p_bosphorussv',
    organization: 'Bosphorus SV',
    cantonRoles: ['SV Operator'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Low' as const,
    notes: 'Co-created NBA Top Shot ($1B+ sales, a16z backed). Ex-White House NEC Fintech office. Ex-Dropbox strategy. Early Multicoin/Polychain investor.',
  },
  {
    id: 'per-017',
    fullName: 'Ivan Reif',
    currentRole: 'Founder / Lead',
    organizationId: 'p_cansaitenkai',
    organization: 'Cansai Tenkai',
    cantonRoles: ['FA Applicant', 'NaaS Operator'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Low' as const,
    notes: 'Cansai iOS wallet. Tenkai GmbH. FA submission 2025-12-15.',
  },
  {
    id: 'per-018',
    fullName: 'Mark Wendland',
    currentRole: 'Chairman & CEO',
    organizationId: 'p_cantonstrategicholdi',
    organization: 'Canton Strategic Holdings',
    cantonRoles: ['SV Operator', 'Treasury Strategy'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'Led $545M placement. Public face of Canton treasury strategy. NASDAQ: CNTN.',
  },
  {
    id: 'per-019',
    fullName: 'Jill Sommers',
    currentRole: 'Board Director',
    organizationId: 'p_cantonstrategicholdi',
    organization: 'Canton Strategic Holdings',
    cantonRoles: ['Governance', 'Regulatory'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'Former CFTC Commissioner. Appointed to board to deepen institutional expertise.',
  },
  {
    id: 'per-020',
    fullName: 'William Wiley',
    currentRole: 'Board Director',
    organizationId: 'p_cantonstrategicholdi',
    organization: 'Canton Strategic Holdings',
    cantonRoles: ['Governance', 'DRW Liaison'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'DRW Chief of Staff. DRW led $545M placement into Canton Strategic Holdings. Board appointment deepens DRW/Canton alignment.',
  },
  {
    id: 'per-021',
    fullName: 'Amar Kuchinad',
    currentRole: 'Global CEO',
    organizationId: 'p_copper',
    organization: 'Copper',
    cantonRoles: ['Custody', 'Collateral Management'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'Copper Global CEO. Named Copper as custodian for Canton Strategic Holdings $545M DAT. ClearLoop integrating with Canton for institutional collateral networks.',
  },
  {
    id: 'per-022',
    fullName: 'Jacob McCrum',
    currentRole: 'Partner Manager',
    organizationId: 'p_digitalasset',
    organization: 'Digital Asset',
    cantonRoles: ['CIP Author (on behalf of new participants)'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'DA Partner Manager. Authors CIPs on behalf of incoming participants. CIP-0095 (Mesh). Key gatekeeper for new SV onboarding — knowing who submits reveals DA\'s pipeline.',
  },
  {
    id: 'per-023',
    fullName: 'Ryo Shimotsu',
    currentRole: 'SBI Digital Assets',
    organizationId: 'p_sbi',
    organization: 'SBI',
    cantonRoles: ['CIP Sponsor'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'Sponsored CIP-0095 (Mesh). SBI Digital Asset Holdings. 下津 龍生.',
  },
  {
    id: 'per-024',
    fullName: 'Amanda Martin',
    currentRole: 'COO, Canton Foundation',
    organizationId: 'p_globalsynchronizerfo',
    organization: 'Global Synchronizer Foundation',
    cantonRoles: ['GSF Operations', 'CIP Lifecycle'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'DrAmandaLMartin. Posted CIP-0095 for discussion. COO Canton Foundation. Oversees governance frameworks, program execution, operational strategy. Ex-Linux Foundation leadership.',
  },
  {
    id: 'per-025',
    fullName: 'Eric Saraniecki',
    currentRole: 'Co-Founder / Head of Network Strategy',
    organizationId: 'p_digitalasset',
    organization: 'Digital Asset',
    cantonRoles: ['CIP Author', 'BD Lead', 'CIP Endorser'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'DA Co-Founder & Head of Network Strategy. +1 773 719 1983. Authors/endorses CIPs for new participants. CIP-0052 (Monstera W5), CIP-0059 (Woodside AI W10), CIP-0081 (YZi Labs W10 — UNIQUE umbrella), CIP-0093 (Bosphorus W6), endorsed CIP-0095 (Mesh W10). Sponsored Monstera validator app. Key gatekeeper for SV onboarding pipeline alongside Jacob McCrum and Wayne Collier. Total weight authored: 31 + 10 endorsed = 41 SV weight through Saraniecki alone.',
  },
  {
    id: 'per-026',
    fullName: 'David Stern',
    currentRole: 'Chairman, Witan Group / Vice Chairman, Sphere Entertainment',
    organizationId: 'p_monstera',
    organization: 'Monstera',
    cantonRoles: ['Principal / Owner'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Critical' as const,
    notes: 'Vice Chairman Sphere Entertainment Co. (Las Vegas Sphere, Sep 2023). Serial entrepreneur: China advisory (2001), founded CMDS (sold to FTSE-250, 2010), Chairman Celestial JV with Fortune 500 (2016), founding investor Canoo EV (NASDAQ 2020, $2.4B valuation). Supervisory Board Holy Fashion Group (Switzerland). Advisory Board Cambridge Judge Business School. Witan Group operates from Hong Kong, Beijing, London, Dubai. CIP-0052 target pipeline includes C-suite/board connections at Tokyo Dome/Mitsui Fudosan, Sun Hung Kai, AirAsia, Mashreq Bank, Dubai Stock Exchange, Abu Dhabi First Bank, Deutsche Bank, Munich Re, Salinas Group.',
  },
  {
    id: 'per-027',
    fullName: 'Chris Matturri',
    currentRole: 'Head of Infrastructure',
    organizationId: 'p_proofgroup',
    organization: 'Proof Group',
    cantonRoles: ['Explorer Lead', 'NaaS Operations'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'Built and launched CantonScan.com — first Canton block explorer (June 2025). Quoted in launch PR: "first time anyone can publicly see activity on Canton Network." Key infrastructure contact at Proof Group.',
  },
  {
    id: 'per-028',
    fullName: 'Dominic Sow',
    currentRole: 'Unknown',
    organizationId: 'p_proofgroup',
    organization: 'Proof Group',
    cantonRoles: ['Content/PR'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Low' as const,
    notes: 'Added the CantonScan launch article. Likely comms or content role at Proof Group.',
  },
  {
    id: 'per-029',
    fullName: 'Faith',
    currentRole: 'Founder / Lead',
    organizationId: 'p_roundbeat',
    organization: 'RoundBeat',
    cantonRoles: ['FA Applicant', 'Validator Operator'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'Primary contact for RoundBeat. @Faith - RoundBeat on Canton Slack. faith@... (email). Experienced node operator across Canton, Ethereum, WalletConnect, Polkadot, Aztec, Gnosis. Submitted FA application 2025-11-05.',
  },
  {
    id: 'per-030',
    fullName: 'Anton Katz',
    currentRole: 'CEO',
    organizationId: 'p_talos',
    organization: 'Talos',
    cantonRoles: ['CIP Author (CIP-0085)'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'CEO of Talos. Authored CIP-0085 (Weight 6.5 SV). Led Coin Metrics acquisition. Premier institutional digital asset trading technology.',
  },
  {
    id: 'per-031',
    fullName: 'Sydney Rice',
    currentRole: 'Head of Network Data and Research',
    organizationId: 'p_talos',
    organization: 'Talos',
    cantonRoles: ['Network Intelligence', 'Data'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'Head of Network Data and Research at Talos. Quoted in SV announcement PR (Nov 2025): "Canton is shaping what the next generation of financial market infrastructure will look like." Likely ex-Coin Metrics team. Runs Canton network intelligence app.',
  },
  {
    id: 'per-032',
    fullName: 'Chris Zuehlke',
    currentRole: 'Unknown (likely GSF/Tokenomics)',
    organizationId: 'p_unknown',
    organization: 'Unknown',
    cantonRoles: ['CIP Editor'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'CIP process reviewer. Flagged CIP-0059 abstract error (Monstera → Woodside AI, Apr 22 #154). Edited CIP-0085 (Talos, Oct 7). Likely GSF Tokenomics committee or DA governance role.',
  },
  {
    id: 'per-033',
    fullName: 'Vinh Nguyen',
    currentRole: 'Unknown (likely GSF/Operations)',
    organizationId: 'p_globalsynchronizerfo',
    organization: 'Global Synchronizer Foundation',
    cantonRoles: ['Vote Administrator', 'FA Process'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'Posts FA vote proposals on mainnet. Created Verigift FA vote (2026-01-01 #321). Handles vote contract creation and timeline management. Likely GSF operations or governance team.',
  },
  {
    id: 'per-034',
    fullName: 'Victor Busson',
    currentRole: 'Chief Marketing Officer',
    organizationId: 'p_taurus',
    organization: 'Taurus',
    cantonRoles: ['CIP Author (CIP-0077)'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'Taurus CMO. Authored CIP-0077 (SV Weight 5). Quoted in SV announcement PR (Nov 2025): "Expanding custody capabilities to Canton ecosystem... creating new institutional use cases." Key commercial contact for Taurus Canton relationship.',
  },
  {
    id: 'per-035',
    fullName: 'Melvis Langyintuo',
    currentRole: 'Executive Director',
    organizationId: 'p_globalsynchronizerfo',
    organization: 'Global Synchronizer Foundation',
    cantonRoles: ['GSF Leadership', 'Partnership Announcements'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'Executive Director, Canton Foundation. Quoted in Taurus SV PR (Nov 2025): "Taurus is one of the most trusted digital asset infrastructure providers to global banks." Key GSF leadership figure for strategic partnership announcements.',
  },
  {
    id: 'per-036',
    fullName: 'Suna Said',
    currentRole: 'Founder & CEO, Nima Capital',
    organizationId: 'p_woodsideainimacapita',
    organization: 'Woodside AI / Nima Capital',
    cantonRoles: ['SV Co-Lead (CIP-0059)'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'Founder/CEO Nima Capital (single-family office, tech disruption focus). Women of Achievement 2015. Board member of several organizations. Co-leads Woodside AI with Don Wilson (DRW) and Edward Hu (ex-OpenAI). Working with Blackstone on Private Credit + Fund Admin for Canton. CIP-0059 (Weight 10).',
  },
  {
    id: 'per-037',
    fullName: 'Edward Hu',
    currentRole: 'AI Researcher / Venture Studio Co-Lead',
    organizationId: 'p_woodsideai',
    organization: 'Woodside AI',
    cantonRoles: ['SV Co-Lead (CIP-0059)', 'AI Strategy'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'Former OpenAI researcher. Invented LoRA and μTransfer — industry-standard AI techniques. PhD in AI, advised by Turing Award winning pioneer. Co-leads Woodside AI with Suna Said and Don Wilson. CIP-0059 (Weight 10). AI/ML expertise applied to Canton Private Credit + Fund Admin infrastructure.',
  },
  {
    id: 'per-038',
    fullName: 'Wayne Collier',
    currentRole: 'Director of Product Management',
    organizationId: 'p_digitalasset',
    organization: 'Digital Asset',
    cantonRoles: ['CIP Process Management'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'DA Director of Product Management. Fixed CIP-0059 abstract error (Monstera → Woodside AI). Confirmed Cumberland supporting + LCV endorsing = ready for SV vote. Active in CIP governance process alongside Eric Saraniecki and Jacob McCrum.',
  },
  {
    id: 'per-039',
    fullName: 'James Lang',
    currentRole: 'Managing Director',
    organizationId: 'p_libertycityventures',
    organization: 'Liberty City Ventures',
    cantonRoles: ['CIP Endorser', 'Governance'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'MD at Liberty City Ventures. Endorsed CIP-0059 (Woodside AI Weight 10). LCV co-led $545M Canton Strategic Holdings placement with DRW. Active governance participant — endorsements signal LCV strategic alignment.',
  },
  {
    id: 'per-040',
    fullName: 'Lionel Yuan',
    currentRole: 'Founder / Lead',
    organizationId: 'p_yuce',
    organization: 'YUCE',
    cantonRoles: ['FA Applicant'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Low' as const,
    notes: 'Primary contact for YUCE. Responsible person on FA submission (2026-01-16, Entry 265). yuce.tradee@...',
  },
  {
    id: 'per-041',
    fullName: 'Changpeng Zhao (CZ)',
    currentRole: 'Founder, YZi Labs (ex-Binance CEO)',
    organizationId: 'p_yzilabs',
    organization: 'YZi Labs',
    cantonRoles: ['Investor', 'Ecosystem Patron'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Critical' as const,
    notes: 'Founded Binance. Stepped down as CEO. YZi Labs (ex-Binance Labs) is his venture arm. $10B+ AUM. Active in investment activities, direct mentorship to founders. Canton backing via DA investment (July 2025) and Temple Digital Group (Oct 2025). One of the most influential figures in crypto backing Canton ecosystem.',
  },
  {
    id: 'per-042',
    fullName: 'Ella Zhang',
    currentRole: 'Head of YZi Labs',
    organizationId: 'p_yzilabs',
    organization: 'YZi Labs',
    cantonRoles: ['Investor Lead'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'Head of YZi Labs. Co-launched Binance Labs with CZ in 2018. First 3 batches of incubation: Polygon, Injective, CertiK, Dune Analytics, Kava, SafePal, Elrond, Nym. Left 2020 for entrepreneurial ventures, returned to lead YZi Labs. Quoted on DA investment: "proud to support bringing tokenised real-world assets into the financial mainstream."',
  },
  {
    id: 'per-043',
    fullName: 'Alex Odagiu',
    currentRole: 'Investment Partner',
    organizationId: 'p_yzilabs',
    organization: 'YZi Labs',
    cantonRoles: ['Investor', 'Deal Lead'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'Investment Partner at YZi Labs. Quoted in Temple Digital Group investment (Oct 2025): "When we backed Canton earlier this year, it became clear that the next step for the ecosystem was execution." Key deal lead for Canton ecosystem investments at YZi Labs.',
  },
  {
    id: 'per-044',
    fullName: 'Evan Varsamis',
    currentRole: 'Co-Founder & CEO',
    organizationId: 'p_templedigitalgroup',
    organization: 'Temple Digital Group',
    cantonRoles: ['Trading Platform Lead'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'Co-Founder & CEO Temple Digital Group. NY-based serial founder/investor. Invested in Rainbow, Discord, Phantom. Previously scaled Gadget Flow to 30M+ monthly reach, exited 2022. Building Canton\'s first native trading platform — privacy-focused CLOB for capital markets. YZi Labs backed. Vision: "Temple to be the core trading engine for use cases traditionally inaccessible on decentralized networks."',
  },
  {
    id: 'per-045',
    fullName: 'Dan Simerman',
    currentRole: 'Co-Founder & CSO',
    organizationId: 'p_templedigitalgroup',
    organization: 'Temple Digital Group',
    cantonRoles: ['Strategy', 'Network Architecture'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'Co-Founder & CSO Temple Digital Group. Previously IOTA Foundation — network architectures and technical strategy for billion-dollar protocols. Prior: consulting at Wells Fargo, lead product role at Condé Nast.',
  },
  {
    id: 'per-046',
    fullName: 'Norbert Vadas',
    currentRole: 'Co-Founder / CIP Lead',
    organizationId: 'p_zenithzkcloud',
    organization: 'Zenith / ZkCloud',
    cantonRoles: ['CIP Author (CIP-0091)'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'High' as const,
    notes: 'CIP-0091 lead author (Zenith SV Weight 10). ZkCloud/Equilibrium Labs. Virtual Blockchains on Canton — EVM/SVM/MoveVM with ZK settlement.',
  },
  {
    id: 'per-047',
    fullName: 'Teemu Paivinen',
    currentRole: 'Co-Founder',
    organizationId: 'p_zenithequilibriumlab',
    organization: 'Zenith / Equilibrium Labs',
    cantonRoles: ['CIP Author (CIP-0091)'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'CIP-0091 co-author. Equilibrium Labs (Helsinki). Prior: EUROe stablecoin, Ethereum Foundation, Fireblocks, Solana Foundation, Zcash work.',
  },
  {
    id: 'per-048',
    fullName: 'Heslin Kim',
    currentRole: 'Co-Founder',
    organizationId: 'p_zenithzkcloud',
    organization: 'Zenith / ZkCloud',
    cantonRoles: ['CIP Author (CIP-0091)'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'CIP-0091 co-author. Zenith/ZkCloud team.',
  },
  {
    id: 'per-049',
    fullName: 'Henri Kamarainen',
    currentRole: 'Co-Founder',
    organizationId: 'p_zenithequilibriumlab',
    organization: 'Zenith / Equilibrium Labs',
    cantonRoles: ['CIP Author (CIP-0091)'],
    eventIds: [],
    mediaIds: [],
    relationshipToFlowryd: 'None' as const,
    priority: 'Medium' as const,
    notes: 'CIP-0091 co-author. Equilibrium Labs (Helsinki).',
  }
];

export const intelMedia: IntelMedia[] = [];

export const intelAnnouncements: IntelAnnouncement[] = [
  {
    id: 'ann-2025-001',
    date: '2025-11',
    participants: ['Flowryd'],
    type: 'Product Launch',
    description: 'Featured App approved: 12 ACCEPT 1 ABSTAIN 0 REJECT',
    impact: 'High' as const,
    notes: 'C7/7RIDGE sponsored',
  },
  {
    id: 'ann-2025-002',
    date: '2025-12-15',
    participants: ['Cansai Tenkai'],
    type: 'Featured App Submission',
    description: 'Cansai (Tenkai GmbH) submitted Featured App application. First native iOS wallet for Canton. Non-custodial, iCloud Keychain sync, $5/mo subscription anti-abuse model. 300+ TestFlight users. Pending committee demo.',
    impact: 'Medium' as const,
    notes: 'Entry ID 172. Submitted 2025-12-15. Subsequently approved — see ANN-2026-001.',
  },
  {
    id: 'ann-2026-001',
    date: '2026-01-13',
    participants: ['Cansai Tenkai'],
    type: 'Featured App Approved',
    description: 'Cansai (Tenkai GmbH) Featured App vote executed. 12 ACCEPT, 0 ABSTAIN, 1 REJECT (13/13 cast). Requested by Digital-Asset-2. Effective 2026-01-13. Sole REJECT: SV-Nodeops-Limited.',
    impact: 'Medium' as const,
    notes: 'ACCEPT: C7, Cumberland (x2), Digital Asset (x2), Five North, GSF, Liberty City Ventures, MPCH, Orb-1, Proof Group, Tradeweb. REJECT: SV-Nodeops-Limited (linked reason). Vote opened 2026-01-05, closed 2026-01-12.',
  },
  {
    id: 'ann-2025-003',
    date: '2025-11-03',
    participants: ['Canton Strategic Holdings', 'DRW', 'Liberty City Ventures'],
    type: 'Investment',
    description: 'Tharimmune (now Canton Strategic Holdings) raised $545M in private placement led by DRW and Liberty City Ventures to launch Canton Coin-based digital asset treasury strategy. First publicly traded company to leverage Canton Coin.',
    impact: 'Critical' as const,
    notes: 'CoinDesk coverage. NASDAQ: THAR at time of placement.',
  },
  {
    id: 'ann-2026-002',
    date: '2026-02-17',
    participants: ['Canton Strategic Holdings'],
    type: 'Corporate Rebrand',
    description: 'Tharimmune rebranded to Canton Strategic Holdings. New NASDAQ ticker CNTN effective 2026-02-18. $55M additional registered offering closed. SV approved. Board expanded: Jill Sommers (ex-CFTC), William Wiley (DRW CoS).',
    impact: 'Critical' as const,
    notes: 'PRNewswire. Canton registered trademark of Digital Asset (Switzerland) GmbH — DA not affiliated with or endorsing operations. Media: Gasthalter & Co.',
  },
  {
    id: 'ann-2025-004',
    date: '2025-11-18',
    participants: ['Copper', 'Canton Strategic Holdings'],
    type: 'Partnership',
    description: 'Copper named custodian for Tharimmune (now Canton Strategic Holdings) $545M Canton Coin treasury strategy. Copper strategic investor. ClearLoop to integrate with Canton Network for institutional collateral management — expanding from multi-sig custody to network-based collateral flows, governance, and validator utility.',
    impact: 'Critical' as const,
    notes: 'Canton Network processing 500K+ daily transactions at time of announcement. Institutions cited: Goldman Sachs, Broadridge, Versana (backed by JPMorgan, Citi, BofA) clearing/settling trillions within first year. Copper Research Issue #53 referenced.',
  },
  {
    id: 'ann-2026-003',
    date: '2026-01-09',
    participants: ['Mesh', 'SBI', 'Digital Asset'],
    type: 'CIP Approved',
    description: 'CIP-0095 approved: Mesh onboarded as outcome-linked Super Validator (max weight 10). Global payments network connecting 400M+ users. Bridges retail crypto liquidity with Canton tokenized assets. Milestones: production integration ($10M min + PR), time acceleration bonus, adoption bonuses up to $6B notional.',
    impact: 'Critical' as const,
    notes: 'Sponsored by SBI (Ryo Shimotsu). Endorsed by DA (Eric Saraniecki). Draft posted by Amanda Martin (GSF COO) 2025-12-04. Created 2025-12-09. Approved 2026-01-09.',
  },
  {
    id: 'ann-2025-005',
    date: '2025-02-10',
    participants: ['Monstera', 'Digital Asset'],
    type: 'Validator Application',
    description: 'Monstera FZE validator application submitted. Digital asset subsidiary of Witan family office (David Stern, MSG board). Sponsored by Eric Saraniecki (DA). Plans to onboard multiple orgs onto Canton. SV CIP expected. USDC activity Q2 2025.',
    impact: 'Medium' as const,
    notes: 'Posted by Amanda Martin (GSF). 1-week implicit approval window. Eric Saraniecki: "legit org with extensive connections." David Stern negotiated Abu Dhabi Sphere deal.',
  },
  {
    id: 'ann-2025-006',
    date: '2025-06-05',
    participants: ['Proof Group', 'Digital Asset'],
    type: 'Product Launch',
    description: 'Proof Group launched CantonScan.com — first-ever block explorer for Canton Network. Real-time balance histories, validator connections, actor profiles, live feed. Proprietary technology for Canton privacy-preserving structure. Eric Saraniecki (DA): "showing the work being done, the progress we\'re making, and the firms involved."',
    impact: 'High' as const,
    notes: 'Chris Matturri (Head of Infrastructure, Proof Group) led build. Etherscan equivalent for Canton. Future features: burn mechanism, transfers & tokenomics, governance & proposals, apps & subscriptions, dedicated Applications Layer.',
  },
  {
    id: 'ann-2025-007',
    date: '2025-11-05',
    participants: ['RoundBeat'],
    type: 'Featured App Application',
    description: 'RoundBeat submitted Featured App application for zero-install on-chain validator monitoring SaaS. CC-only subscriptions first 6 months. Multi-chain (Canton, Aztec, Celestia). Posted by Amanda Martin (GSF). Next step: demo at committee meeting.',
    impact: 'Medium' as const,
    notes: 'Contact: Faith. MainNet target Nov 10, 2025. 40 daily txns/user. FA leverage: "Without FA status, would likely pursue another chain." Cantara launch planned.',
  },
  {
    id: 'ann-2026-004',
    date: '2026-03-02',
    participants: ['Send'],
    type: 'Rebrand / Product Consolidation',
    description: 'Canton Wallet amalgamated into Send app. All product updates, announcements, support now from @send. Canton Wallet Twitter sunsetting. Roadmap: CUSD stablecoin, Send Safe multi-sig, Pool Party AMM DEX, $SEND/$CC staking, iOS/Android apps, full Canton Network account migration. $CC drip program transitioning to sustainable reward mechanisms.',
    impact: 'High' as const,
    notes: 'Consolidation of strengths. "Next era of private, programmable finance." Pool Party = new AMM DEX on Canton (alongside Tradecraft). CUSD = new privacy-first stablecoin. Staking for both $SEND and $CC.',
  },
  {
    id: 'ann-2025-008',
    date: '2025-12-21',
    participants: ['Silvana'],
    type: 'Featured App Application',
    description: 'Silvana Book FA application submitted. Privacy-first orderbook with off-chain matching, atomic DVP settlement for CIP-56 tokens, ZKP proving agents. First customers: Loop wallet (Five North) users. MainNet target Jan 5, 2026. CC subscriptions + Activity Markers.',
    impact: 'Medium' as const,
    notes: 'Entry 190. Posted by Amanda Martin (GSF). Next step: demo at committee. ZKP angle is unique — aggregated trading data proofs without disclosing private transaction info. Agentic trading/settlement.',
  },
  {
    id: 'ann-2025-009',
    date: '2025-11-12',
    participants: ['Talos', 'Coin Metrics'],
    type: 'Super Validator Launch',
    description: 'Talos announced operating as Super Validator on Canton Network following Coin Metrics acquisition. Combined entity provides SV operations, network data intelligence, institutional trading/settlement infrastructure. CC trading live day one via 60+ liquidity sources (spot: Bybit, Gate.io, Kucoin, Kraken, MEXC; perps: Binance Futures, Bybit, Phemex, OKX). pX agency desk to route institutional settlement through Canton.',
    impact: 'Critical' as const,
    notes: 'Coin Metrics SV since March 2025 (CIP-0046). Network intelligence app launched July 2025. CIP-0085 approved Oct 9, 2025. Weight 6.5 outcome-linked. Sydney Rice quoted. Massive institutional CC liquidity unlock.',
  },
  {
    id: 'ann-2025-010',
    date: '2025-12-31',
    participants: ['LILIZ (Verigift)'],
    type: 'Featured App Approved',
    description: 'LILIZ Verigift app approved as Featured App by Tokenomics Committee. Fundraising platform with charity badges. Vote: 12 ACCEPT, 1 REJECT (SV-Nodeops-Limited). Effective 2026-01-09.',
    impact: 'Low' as const,
    notes: 'Vote initiated by Five-North-1. Posted by Vinh Nguyen. SV-Nodeops-Limited sole rejector (same pattern as Cansai vote). 13/13 SVs cast votes.',
  },
  {
    id: 'ann-2025-011',
    date: '2025-11-25',
    participants: ['Taurus', 'Global Synchronizer Foundation'],
    type: 'Super Validator + Custody Launch',
    description: 'Taurus announced as Super Validator and strategic partner on Canton Network. Canton Token Standard custody support live. FINMA-regulated. Clients: CACEIS, Deutsche Bank, State Street, Santander. Backed by Deutsche Bank, UBS, Lombard Odier, Pictet, Arab Bank Switzerland. $6T+ tokenized assets cited on Canton at time of announcement.',
    impact: 'Critical' as const,
    notes: 'Victor Busson (CMO) and Melvis Langyintuo (GSF Exec Director) quoted. CIP-0077 approved Sep 12. Brings tier-1 banking custody infrastructure into Canton. 13 offices globally. ~100 employees. Full platform: PROTECT, EXPLORER, CAPITAL, NETWORK, PRIME.',
  },
  {
    id: 'ann-2025-012',
    date: '2025-04-21',
    participants: ['Woodside AI', 'Digital Asset', 'Cumberland', 'Liberty City Ventures'],
    type: 'CIP Proposal (SV Weight 10)',
    description: 'CIP-0059 opened for discussion: Woodside AI SV Weight 10 — highest in ecosystem. Venture studio led by Suna Said (Nima Capital), Don Wilson (DRW), Edward Hu (ex-OpenAI/LoRA). Building Private Credit + Fund Admin infrastructure with Blackstone. Middle East assets: mortgages, payment securitization. DA sponsor, Cumberland supporting, LCV endorsed.',
    impact: 'Critical' as const,
    notes: 'Author: Eric Saraniecki. Posted by Amanda Martin. GitHub PR #52. Abstract originally said "Monstera" — fixed by Wayne Collier. James Lang (LCV MD) endorsed. Ready for SV vote. Fund Admin MVP = +3 weight = single largest milestone. Target GPs: Blackstone, Ares, Apollo, KKR, Goldman, Oaktree, Carlyle.',
  },
  {
    id: 'ann-2026-005',
    date: '2026-01-16',
    participants: ['YUCE'],
    type: 'Featured App Application',
    description: 'YUCE FA application submitted. First institutional prediction market on Canton. Privacy-preserving risk pricing. CC + Activity Markers. Global Awareness Layer vision. MainNet within 1 month.',
    impact: 'Medium' as const,
    notes: 'Entry 265. Contact: Lionel Yuan. Next step: demo at committee. Prediction Markets is a unique capability on Canton — fills ecosystem gap.',
  },
  {
    id: 'ann-2025-013',
    date: '2025-07-04',
    participants: ['YZi Labs', 'Digital Asset', 'DRW', 'Tradeweb', 'Goldman Sachs', 'DTCC', 'Citadel'],
    type: 'Investment Round',
    description: 'YZi Labs (ex-Binance Labs, CZ) invested in Digital Asset alongside DRW, Tradeweb, Goldman Sachs, DTCC, Citadel. Funding to expand Canton Network infrastructure and accelerate institutional onboarding. Ella Zhang: "bringing tokenised real-world assets into the financial mainstream." Yuval Rooz: "advancing mission to bring trillions more in RWA on-chain."',
    impact: 'Critical' as const,
    notes: 'DA investor syndicate revealed: DRW, Tradeweb, Goldman Sachs, DTCC, Citadel, YZi Labs. Reported by Jack McRae, US Reporter. Binance/CZ ecosystem directly backing Canton infrastructure.',
  },
  {
    id: 'ann-2025-014',
    date: '2025-10-16',
    participants: ['YZi Labs', 'Temple Digital Group'],
    type: 'Investment',
    description: 'YZi Labs invested in Temple Digital Group, creator of Canton Network\'s first native trading platform. Privacy-focused CLOB for institutional capital markets. Follows YZi Labs July 2025 backing of Canton Network. Temple plans: asset issuance, perpetual futures, cross-network trade routing.',
    impact: 'High' as const,
    notes: 'Alex Odagiu (YZi Investment Partner) deal lead. Evan Varsamis CEO, Dan Simerman CSO. Vision: NASDAQ + DTCC for regulated blockchain. Temple aims to bridge TradFi and DeFi on Canton.',
  },
  {
    id: 'ann-2026-006',
    date: '2026-01-27',
    participants: ['YZi Labs', 'Canton Foundation'],
    type: 'Super Validator Launch',
    description: 'YZi Labs (ex-Binance Labs, CZ) joins Canton Network as Super Validator via CIP-0081. Weight 10, unique umbrella program. $10B+ AUM. 300+ portfolio projects. Focus: portfolio integration via Canton privacy layers, infrastructure expansion, market access/liquidity. Canton\'s neutrality preserved — diversifies validator set credibility for institutional participants.',
    impact: 'Critical' as const,
    notes: 'Covered by CoinTrust (Jan 27) and BlockchainReporter (Jan 26). CIP-0081 authored by Eric Saraniecki. Approved Sep 26, 2025 (3-day turnaround). "Substantive governance enhancement rather than symbolic." "Larger movement of institutional investors transitioning from passive to active." Professionalization of validator sets trend.',
  }
];

export const cipRegistry: CIPRecord[] = [
  {
    cipNumber: 'CIP-0009',
    title: 'Broadridge DLR Super Validator',
    proposer: 'Broadridge',
    type: 'Super Validator',
    svWeightRequested: 10,
    status: 'Approved',
    description: 'DLR Registry',
  },
  {
    cipNumber: 'CIP-0010',
    title: 'Liberty City Ventures SV',
    proposer: 'Liberty City Ventures',
    type: 'Super Validator',
    svWeightRequested: 10,
    status: 'Approved',
    description: 'Inner circle SV',
  },
  {
    cipNumber: 'CIP-0015',
    title: 'Copper SV',
    proposer: 'Copper',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    voteResult: '13/13',
    svNodeopsVote: 'ACCEPT',
    description: 'Also CIP-0039 Clearloop +1 weight',
  },
  {
    cipNumber: 'CIP-0016',
    title: 'Dfns SV',
    proposer: 'Dfns',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    description: 'Wallet infrastructure',
  },
  {
    cipNumber: 'CIP-0018',
    title: 'Tradeweb SV',
    proposer: 'Tradeweb',
    type: 'Super Validator',
    svWeightRequested: 10,
    status: 'Approved',
    description: 'Inner circle SV',
  },
  {
    cipNumber: 'CIP-0019',
    title: '7RIDGE C7 SV',
    proposer: '7RIDGE C7',
    type: 'Super Validator',
    svWeightRequested: 10,
    status: 'Approved',
    description: 'Flowryd sponsor; 7Trust identity',
  },
  {
    cipNumber: 'CIP-0032',
    title: 'Lukka SV',
    proposer: 'Lukka',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    description: 'Crypto accounting',
  },
  {
    cipNumber: 'CIP-0034',
    title: 'Proof Group SV',
    proposer: 'Proof Group',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    description: 'Inner circle SV',
  },
  {
    cipNumber: 'CIP-0035',
    title: 'Five North SV',
    proposer: 'Five North',
    type: 'Super Validator',
    svWeightRequested: 3,
    status: 'Approved',
    description: 'Lighthouse explorer; 5N Loop wallet',
  },
  {
    cipNumber: 'CIP-0036',
    title: 'Kiln SV',
    proposer: 'Kiln',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    description: 'Staking infrastructure',
  },
  {
    cipNumber: 'CIP-0037',
    title: 'Obsidian SV',
    proposer: 'Obsidian',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    description: 'Dev tooling',
  },
  {
    cipNumber: 'CIP-0040',
    title: 'Deribit SV',
    proposer: 'Deribit',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    description: 'Derivatives exchange',
  },
  {
    cipNumber: 'CIP-0041',
    title: 'Circle USDCx SV',
    proposer: 'Circle USDCx',
    type: 'Super Validator',
    svWeightRequested: 10,
    status: 'Approved',
    voteResult: '13/13',
    svNodeopsVote: 'ACCEPT',
    description: 'USDC Bridge Ethereum to Canton; DA partnership',
  },
  {
    cipNumber: 'CIP-0043',
    title: 'TRM SV',
    proposer: 'TRM',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    description: 'Compliance',
  },
  {
    cipNumber: 'CIP-0044',
    title: 'Elliptic SV',
    proposer: 'Elliptic',
    type: 'Super Validator',
    svWeightRequested: 0.5,
    status: 'Approved',
    description: 'KYC AML',
  },
  {
    cipNumber: 'CIP-0046',
    title: 'Coin Metrics SV',
    proposer: 'Coin Metrics',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    voteResult: '13/13',
    svNodeopsVote: 'ACCEPT',
    description: 'CM Canton Data App; DA Billing integration',
  },
  {
    cipNumber: 'CIP-0052',
    title: 'Add Monstera as an SV of Weight 5',
    proposer: 'Monstera (Eric Saraniecki)',
    type: 'Governance',
    svWeightRequested: 5,
    status: 'Final',
    voteResult: 'Approved 2025-05-13',
    description: 'Outcome-linked SV: +0.5 per approved strategic participant onboarded onto Canton (USDC/USYC integration + first MainNet tx). Max weight 5 within 180 days. David Stern (Sphere Entertainment VC, Witan Group) leveraging global network: Tokyo Dome, Mashreq Bank, Dubai Stock Exchange, Deutsche Bank, Munich Re, Salinas Group, AirAsia, Sun Hung Kai.',
    notes: 'Author: Eric Saraniecki. Created 2025-03-14. Updated 2025-03-19, 2025-04-14, 2025-05-13, 2025-08-07. Monthly progress to Tokenomics committee. Subject to CIP-0045. Escrow SV mechanics.',
  },
  {
    cipNumber: 'CIP-0053',
    title: 'AngelHack SV',
    proposer: 'AngelHack',
    type: 'Super Validator',
    svWeightRequested: 2.5,
    status: 'Approved',
    ccDistributed: 33164580.92,
    description: 'Developer ecosystem',
  },
  {
    cipNumber: 'CIP-0054',
    title: 'Figment SV',
    proposer: 'Figment',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    description: 'Staking infrastructure',
  },
  {
    cipNumber: 'CIP-0055',
    title: 'Bitwave SV',
    proposer: 'Bitwave',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    voteResult: '13/13',
    svNodeopsVote: 'ACCEPT',
    description: 'Crypto accounting tax; Payments coming; C7 sponsored',
  },
  {
    cipNumber: 'CIP-0057',
    title: 'Quantstamp SV',
    proposer: 'Quantstamp',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    description: 'Security audit',
  },
  {
    cipNumber: 'CIP-0058',
    title: 'IntellectEU SV',
    proposer: 'IntellectEU',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    voteResult: '13/13',
    svNodeopsVote: 'ACCEPT',
    description: 'Catalyst Package Manager; Flowryd deployment partner',
  },
  {
    cipNumber: 'CIP-0059',
    title: 'Add Woodside AI as an SV of Weight 10',
    proposer: 'Woodside AI (Eric Saraniecki)',
    type: 'Governance',
    svWeightRequested: 10,
    status: 'Draft',
    voteResult: 'Pending (Cumberland supporting, LCV endorsed)',
    description: 'Highest weight CIP at 10. Venture studio (Suna Said, Don Wilson/DRW, Edward Hu/ex-OpenAI). Private Credit + Fund Admin with Blackstone (or Ares, Apollo, KKR, Goldman, Oaktree, Carlyle). Milestones: PC GP commitment (+1), PC MVP (+1), PC TVL $2B (+0.5/$500M max +2), FA GP commitment (+1), FA MVP live (+3), Canton adoption (+0.5/participant max +2). Middle East assets: mortgages, payment securitization.',
    notes: 'Author: Eric Saraniecki. Created 2025-04-21. DA sponsor. Cumberland supporting. LCV endorsed (James Lang MD). Abstract error: originally said "Monstera" — fixed by Wayne Collier (DA). Amanda Martin posted. Fund Admin MVP = +3 weight = single largest milestone in any CIP. Subject to CIP-0045.',
  },
  {
    cipNumber: 'CIP-0060',
    title: 'Zero Hash SV',
    proposer: 'Zero Hash',
    type: 'Super Validator',
    svWeightRequested: 7.5,
    status: 'Approved',
    ccDistributed: 6299943.61,
    description: 'Crypto infrastructure',
  },
  {
    cipNumber: 'CIP-0061',
    title: 'Chainlink SV',
    proposer: 'Chainlink',
    type: 'Super Validator',
    svWeightRequested: 7.5,
    status: 'Approved',
    description: 'Also CIP-0065 +3 weight',
  },
  {
    cipNumber: 'CIP-0063',
    title: 'Kaiko Price Feed SV',
    proposer: 'Kaiko',
    type: 'Super Validator',
    svWeightRequested: 6.5,
    status: 'Approved',
    ccDistributed: 53904399.35,
    description: '81.88M CC holdings; kaiko-data.unverified.cns',
  },
  {
    cipNumber: 'CIP-0065',
    title: 'LayerZero + Wormhole Bridge SVs',
    proposer: 'LayerZero + Wormhole',
    type: 'Super Validator',
    svWeightRequested: 3,
    status: 'Approved',
    description: 'Bridge',
  },
  {
    cipNumber: 'CIP-0069',
    title: 'Ledger SV',
    proposer: 'Ledger',
    type: 'Super Validator',
    svWeightRequested: 5,
    status: 'Approved',
    ccDistributed: 2497195.19,
    description: 'Major wallet provider',
  },
  {
    cipNumber: 'CIP-0071',
    title: 'Ubyx SV',
    proposer: 'Ubyx',
    type: 'Super Validator',
    svWeightRequested: 5,
    status: 'Approved',
    description: 'Settlement clearing; Tony McLaughlin',
  },
  {
    cipNumber: 'CIP-0072',
    title: 'Fireblocks SV',
    proposer: 'Fireblocks',
    type: 'Super Validator',
    svWeightRequested: 5,
    status: 'Approved',
    ccDistributed: 2.08,
    description: 'Wallet support milestone complete',
  },
  {
    cipNumber: 'CIP-0074',
    title: 'BitGo SV',
    proposer: 'BitGo',
    type: 'Super Validator',
    svWeightRequested: 5,
    status: 'Approved',
    voteResult: '13/13',
    svNodeopsVote: 'ACCEPT',
    description: 'First US qualified custodian; NYSE BTGO; supports CC and USDCx and CBTC',
  },
  {
    cipNumber: 'CIP-0075',
    title: 'Zodia Custody SV',
    proposer: 'Zodia Custody',
    type: 'Super Validator',
    svWeightRequested: 5,
    status: 'Approved',
    voteResult: '13/13',
    svNodeopsVote: 'ACCEPT',
    description: 'Bank-bred StanChart NT JV; Interchange settlement',
  },
  {
    cipNumber: 'CIP-0076',
    title: 'Hypernative SV',
    proposer: 'Hypernative',
    type: 'Super Validator',
    svWeightRequested: 1,
    status: 'Approved',
    ccDistributed: 10879509.77,
    description: 'Security monitoring',
  },
  {
    cipNumber: 'CIP-0077',
    title: 'Add Taurus as an SV of Weight 5',
    proposer: 'Taurus (Victor Busson)',
    type: 'Governance',
    svWeightRequested: 5,
    status: 'Approved',
    voteResult: 'Approved 2025-09-12',
    svNodeopsVote: 'ACCEPT',
    ccDistributed: 23578815.54,
    description: 'Taurus commits to integrate Canton Network within platform for banking clients. Milestones: (1) Custody — EXPLORER + PROTECT integration for Canton Token Standard (+1, 180d). (2) Acceleration bonus — max +2 if delivered in 60d (linear sliding, at least 1 customer live on MainNet). (3) Adoption bonus — +0.5 per $1.5B assets transferred OR per approved participant issuing >$1M TVL on Canton via Taurus (max +2 total, 180d from custody go-live).',
    notes: 'Author: Victor Busson (CMO). Created 2025-08-26. Approved 2025-09-12. 60-day progress to Tokenomics. Subject to CIP-0045. Escrow SV mechanics. Clients: CACEIS, Deutsche Bank, State Street, Santander.',
  },
  {
    cipNumber: 'CIP-0080',
    title: 'Republic SV',
    proposer: 'Republic',
    type: 'Super Validator',
    svWeightRequested: 6,
    status: 'Approved',
    ccDistributed: 2560753.84,
    description: 'Also Republic Wallet FA; T-RIZE distribution partner',
  },
  {
    cipNumber: 'CIP-0081',
    title: 'Add YZi Labs as Weight 10 SV',
    proposer: 'YZi Labs (Eric Saraniecki)',
    type: 'Governance',
    svWeightRequested: 10,
    status: 'Approved',
    voteResult: 'Approved 2025-09-26',
    description: 'UNIQUE umbrella milestone-based program. Weight 10 max, 365-day term. Open-ended: YZi can pivot to highest-leverage network needs without new CIP. Per-initiative pre-approval from Tokenomics Committee with defined outcomes, evidence, timeline, weight, verification. Confidential initiatives allowed (redacted public summaries). Double-counting protection. Scope: adoption, ecosystem investment, infrastructure/tooling, liquidity/access. Escrow SV mechanics.',
    notes: 'Author: Eric Saraniecki. Created 2025-09-23. Approved 2025-09-26 (3-day approval — fastest). FIRST umbrella CIP — no fixed deliverables, flexible commitment. SV announced Jan 26-27, 2026 (CoinTrust, BlockchainReporter). $10B+ AUM. 300+ portfolio projects. Motivation: "rigid, one-off CIPs are a poor fit." Committee responds with clear weight + acceptance tests. Verified weight transferred from escrow.',
  },
  {
    cipNumber: 'CIP-0083',
    title: 'DTCC SV',
    proposer: 'DTCC',
    type: 'Super Validator',
    status: 'Approved',
    description: 'Major clearing house',
  },
  {
    cipNumber: 'CIP-0085',
    title: 'Add Talos as Weight 6.5 SV',
    proposer: 'Talos (Anton Katz)',
    type: 'Governance',
    svWeightRequested: 6.5,
    status: 'Approved',
    voteResult: 'Approved 2025-10-09',
    description: 'Preserves Coin Metrics Weight 1.0 (CIP-0046). Adds outcome-linked max +6.5. Two initiatives: (1) CC platform-wide support — Security Master, exchange/OTC/custody adapters, ≤5 biz day venue activation. (2) pX agency desk — private institutional settlement on Canton. Milestones: CC readiness +1 (90d), CC acceleration max +1, CC activation +0.5, CC adoption +0.5/$25M (max +1), pX readiness +1 (180d), pX acceleration max +1, pX adoption +0.5/$1.5B (max +1).',
    notes: 'Author: Anton Katz. Created 2025-09-08. Edited Chris Zuehlke 2025-10-07. Approved 2025-10-09. CC0-1.0. Subject to CIP-0045. Escrow SV mechanics. 60+ liquidity sources. CC live on Bybit, Gate.io, Kucoin, Kraken, MEXC (spot) + Binance Futures, Bybit, Phemex, OKX (perps).',
  },
  {
    cipNumber: 'CIP-0087',
    title: 'Hex Trust SV',
    proposer: 'Hex Trust',
    type: 'Super Validator',
    svWeightRequested: 3,
    status: 'Approved',
    description: 'Asia custody',
  },
  {
    cipNumber: 'CIP-0090',
    title: 'USDT0 Tether SV',
    proposer: 'USDT0 Tether',
    type: 'Super Validator',
    svWeightRequested: 10,
    status: 'Approved',
    description: 'Outcome-linked',
  },
  {
    cipNumber: 'CIP-0091',
    title: 'Add Zenith as an SV of Weight 10',
    proposer: 'Zenith (Norbert Vadas, Teemu Paivinen, Heslin Kim, Henri Kamarainen)',
    type: 'Governance',
    svWeightRequested: 10,
    status: 'Approved',
    voteResult: 'Approved 2025-11-04',
    description: 'Virtual Blockchains (VBs) on Canton. EVM/SVM/MoveVM execution environments with atomic Daml composability and ZK-proof settlement. Weight 10 split: Integration 4 (MVP +1, Mainnet composability +3) + Growth/Adoption 6 (enterprise deployments max +1.5, CC burn max +3, RWA $1B+ issuance +1.5). New Daml primitives: external_call(), verify(). Based on Polyglot Canton Whitepaper. MiCA-compliant. RISC-V. Connects Ethereum, Base, Solana to Canton.',
    notes: 'Authors: Norbert Vadas, Teemu Paivinen, Heslin Kim, Henri Kamarainen. Created 2025-10-17. Rewritten 2025-10-28. Approved 2025-11-04. ZkCloud/Equilibrium Labs (Helsinki). Prior: EUROe, ETH Foundation, Fireblocks, Solana Foundation, Zcash. CC burn max +3 = largest burn incentive. RWA $1B target. Escrow SV mechanics.',
  },
  {
    cipNumber: 'CIP-0093',
    title: 'Add Bosphorus SV (BSV) as a Super Validator Max Weight 6',
    proposer: 'Bosphorus SV (Eric Saraniecki)',
    type: 'Governance / Super Validator',
    svWeightRequested: 6,
    status: 'Approved',
    voteResult: 'Approved 2025-11-24',
    description: 'Eurasia/GCC SV. Outcome-linked: +0.5 weight per $2M inelastic burn (max +5), +1 for TRY govt bond issuance >$10M TVL at 18mo. Focus: tokenized US Treasuries, stablecoin settlement, wallet/card issuance, on-chain lending, sovereign instruments. Target: Turkiye, GCC, Central Asia.',
    notes: 'Team: Suleyman Onay (Colendi MD, Harvard MBA, ex-BCG), Ilker Zorluoglu (ex-Outlier Ventures MENA), Ari Nazir (co-created NBA Top Shot, ex-White House NEC). Created 2025-11-07. Approved 2025-11-24. Subject to CIP-0045 operating requirements. Must operate own SV within 6mo of crossing weight 2.5.',
  },
  {
    cipNumber: 'CIP-0094',
    title: 'Blockdaemon SV',
    proposer: 'Blockdaemon',
    type: 'Super Validator',
    svWeightRequested: 5,
    status: 'Approved',
    description: 'Node infrastructure',
  },
  {
    cipNumber: 'CIP-0095',
    title: 'Onboard Mesh to Canton — Outcome-Linked SV Weight (Max 10)',
    proposer: 'Mesh (Jacob McCrum)',
    type: 'Governance / Ecosystem',
    svWeightRequested: 10,
    status: 'Approved',
    voteResult: 'Approved 2026-01-09',
    description: 'Outcome-linked SV: +2 production integration (≤180 days, $10M min + PR), +2 time acceleration (Day 60-180 linear), +3 adoption ($0.5/$500M cap $3B), +3 adoption ($0.5/$1B cap $6B). Bridges 400M+ users, 300+ wallets/exchanges. Mobilizes USDT/USDC/PYUSD on Canton.',
    notes: 'Sponsored by SBI (Ryo Shimotsu). Endorsed by DA (Eric Saraniecki). Created 2025-12-09. Approved 2026-01-09. Subject to CIP-0045. Escrow SV mechanics.',
  },
  {
    cipNumber: 'CIP-0097',
    title: 'Nasdaq SV',
    proposer: 'Nasdaq',
    type: 'Super Validator',
    status: 'Approved',
    description: 'Exchange infrastructure',
  },
  {
    cipNumber: 'CIP-0102',
    title: 'Tharimmune SV',
    proposer: 'Tharimmune',
    type: 'Super Validator',
    svWeightRequested: 4,
    status: 'Approved',
    description: 'Approved',
  }
];

// ── Lookup Helpers ──────────────────────────────────────

export function getPersonById(id: string): IntelPerson | undefined {
  return intelPeople.find(p => p.id === id);
}

export function getOrgById(id: string): Participant | undefined {
  return participants.find(p => p.id === id);
}

export function getOrgByName(name: string): Participant | undefined {
  return participants.find(p => p.name.toLowerCase() === name.toLowerCase());
}

export function getPeopleForEvent(eventId: string): IntelPerson[] {
  return intelPeople.filter(p => p.eventIds.includes(eventId));
}

export function getEventsForPerson(personId: string): IntelEvent[] {
  const person = getPersonById(personId);
  if (!person) return [];
  return intelEvents.filter(e => person.eventIds.includes(e.id));
}

export function getMediaForPerson(personId: string): IntelMedia[] {
  const person = getPersonById(personId);
  if (!person) return [];
  return intelMedia.filter(m => person.mediaIds.includes(m.id));
}

export function getOrgsForEvent(eventId: string): Participant[] {
  const event = intelEvents.find(e => e.id === eventId);
  if (!event) return [];
  return event.cantonOrgIds.map(id => participants.find(p => p.id === id)).filter(Boolean) as Participant[];
}

export function getAnnouncementsForOrg(orgName: string): IntelAnnouncement[] {
  return intelAnnouncements.filter(a => 
    a.participants.some(p => p.toLowerCase().includes(orgName.toLowerCase()))
  );
}

export function getCIPsForOrg(orgName: string): CIPRecord[] {
  return cipRegistry.filter(c => 
    c.proposer.toLowerCase().includes(orgName.toLowerCase())
  );
}
