// Canton Templates, Flows, and Flow Steps Data
// Generated from Liz's FLOWRYDDATA CSVs

export interface CantonTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  participantColumn: string;
  foundationCategoryMap: string;
}

export interface CantonFlow {
  id: string;
  name: string;
  category: string;
  description: string;
  stepCount: number;
  source: string;
  status: 'PROVEN' | 'DESIGN' | 'ACTIVE' | 'PLANNED';
}

export interface CantonFlowStep {
  flowId: string;
  step: number;
  templateName: string;
  action: string;
  inputs: string;
  outputs: string;
  triggersNext: string;
  cantonPrivacy: string;
  notes?: string;
}

export interface TemplateParticipantMapping {
  templateName: string;
  participantId: string;
  organization: string;
  isSV: boolean;
  isValidator: boolean;
  cantonRole: string;
  foundationCategory?: string;
}

export const cantonTemplates: CantonTemplate[] = [
  {
    id: 'TMPL-001',
    name: 'Custody Role',
    description: 'Safekeep digital and tokenized assets. Hot/cold storage, key management, institutional-grade security.',
    category: 'Asset Safekeeping',
    participantColumn: 'Custody',
    foundationCategoryMap: 'Custodians & Wallets',
  },
  {
    id: 'TMPL-002',
    name: 'Settlement Rail',
    description: 'Provide cash leg for transactions. Stablecoins, deposit tokens, tokenized commercial bank deposits. Also handles atomic DvP execution.',
    category: 'Cash & Settlement',
    participantColumn: 'Settlement',
    foundationCategoryMap: 'DeFi',
  },
  {
    id: 'TMPL-003',
    name: 'Registry Role',
    description: 'Legal record of ownership. CSD functions. Issuance registration, dematerialisation, corporate actions processing.',
    category: 'Asset Safekeeping',
    participantColumn: 'Registry',
    foundationCategoryMap: 'Tokenization',
  },
  {
    id: 'TMPL-004',
    name: 'Tokenize / Issuer Role',
    description: 'Tokenize assets on-chain. Create primary market instruments. Structure and deploy token smart contracts.',
    category: 'Asset Creation',
    participantColumn: 'Issuer',
    foundationCategoryMap: 'Tokenization',
  },
  {
    id: 'TMPL-005',
    name: 'Exchange Role',
    description: 'Order matching, price discovery, execution venues. Primary distribution and secondary market trading.',
    category: 'Execution',
    participantColumn: 'Exchange',
    foundationCategoryMap: 'Trading & Exchanges',
  },
  {
    id: 'TMPL-006',
    name: 'Compliance Check',
    description: 'AML/KYC screening, transaction monitoring, regulatory checks. Sanctions screening. On-chain compliance verification.',
    category: 'Risk & Compliance',
    participantColumn: 'Compliance',
    foundationCategoryMap: 'Data & Analytics',
  },
  {
    id: 'TMPL-007',
    name: 'Wallet Provider',
    description: 'Key management, transaction signing, user-facing asset interface. Self-custody and managed custody options.',
    category: 'Infrastructure',
    participantColumn: 'Wallet',
    foundationCategoryMap: 'Custodians & Wallets',
  },
  {
    id: 'TMPL-008',
    name: 'Liquidity Provider',
    description: 'Provide trading liquidity and market depth. OTC and on-venue. Includes dedicated market makers with continuous two-sided quotes.',
    category: 'Execution',
    participantColumn: 'Liquidity_Provider',
    foundationCategoryMap: 'Trading & Exchanges',
  },
  {
    id: 'TMPL-009',
    name: 'Collateral Agent',
    description: 'Manage collateral pools, margin calls, haircuts, reuse/rehypothecation. Tri-party and bilateral collateral management.',
    category: 'Collateral & Financing',
    participantColumn: 'Collateral_Agent',
    foundationCategoryMap: 'Tokenization',
  },
  {
    id: 'TMPL-010',
    name: 'Oracle / Pricing',
    description: 'Asset pricing, mark-to-market, NAV calculation, reference data. On-chain verifiable data feeds.',
    category: 'Data & Analytics',
    participantColumn: 'Valuation_Pricing',
    foundationCategoryMap: 'Bridges/Oracles',
  },
  {
    id: 'TMPL-011',
    name: 'Identity Provider',
    description: 'Issue on-chain identity credentials. KYC/identity verification. Verifiable credential issuance for investor onboarding.',
    category: 'Risk & Compliance',
    participantColumn: 'Identity_Provider',
    foundationCategoryMap: 'NaaS',
  },
  {
    id: 'TMPL-012',
    name: 'Explorer',
    description: 'Block explorers, network analytics, dashboards, ecosystem reporting. Visibility into on-chain activity, transaction flows, and network health.',
    category: 'Analytics',
    participantColumn: 'Data_Oracle',
    foundationCategoryMap: 'Blockchain Explorers',
  },
  {
    id: 'TMPL-013',
    name: 'Bridge Role',
    description: 'Cross-chain and cross-network asset transfers. Interoperability layer enabling assets to move between Canton and other networks or between Canton applications.',
    category: 'Infrastructure',
    participantColumn: 'Bridge',
    foundationCategoryMap: 'Bridges/Oracles',
  }
];

export const cantonFlows: CantonFlow[] = [
  {
    id: 'FLOW-001',
    name: 'Intraday Repo',
    category: 'Collateral Mobility',
    description: 'Finance tokenized securities against digital cash. Intraday, 24/7, with collateral reuse. Proven across 4 Canton working group rounds (Aug 2025 – Feb 2026).',
    stepCount: 8,
    source: 'Canton Global Collateral Network Rounds 1-4',
    status: 'PROVEN' as const,
  },
  {
    id: 'FLOW-002',
    name: 'Bilateral Derivatives Margin',
    category: 'Derivatives Collateral',
    description: 'ISDA CSA-compliant on-chain margin management for OTC bilateral derivatives. 24/7 margining cycles with automated pledging and novel collateral types.',
    stepCount: 6,
    source: 'Canton Derivatives Collateral Initiative (Jan 2025–)',
    status: 'DESIGN' as const,
  },
  {
    id: 'FLOW-003',
    name: 'Token Issuance',
    category: 'Corporate Finance',
    description: 'Primary market issuance of tokenized securities. Structure, register, verify investors, distribute, settle, custody.',
    stepCount: 7,
    source: 'OG Capital Markets Use Cases — Issuance / Tokenization',
    status: 'ACTIVE' as const,
  },
  {
    id: 'FLOW-004',
    name: 'Cross-Border Collateral Transfer',
    category: 'Collateral Mobility',
    description: 'Move collateral across jurisdictions. Tokenize in one CSD, settle against foreign currency cash in another. Multi-asset, multi-currency.',
    stepCount: 6,
    source: 'Canton Working Group Round 3-4 (Jan-Feb 2026)',
    status: 'PROVEN' as const,
  },
  {
    id: 'FLOW-005',
    name: 'Securities Lending',
    category: 'Collateral Mobility',
    description: 'Borrow and lend tokenized securities on-chain. Automated locate, pre-borrow, settlement, and return.',
    stepCount: 0,
    source: 'OG Capital Markets Use Cases — Securities Lending',
    status: 'PLANNED' as const,
  },
  {
    id: 'FLOW-006',
    name: 'Fund Subscription / Redemption',
    category: 'Investing',
    description: 'Tokenized fund subscription and redemption. NAV calculation, settlement, transfer agent processing.',
    stepCount: 0,
    source: 'OG Capital Markets Use Cases — Funds Services',
    status: 'PLANNED' as const,
  },
  {
    id: 'FLOW-007',
    name: 'Secondary Trading',
    category: 'Trading & Exchange',
    description: 'Secondary market trading of tokenized securities. Order routing, execution, clearing, settlement.',
    stepCount: 0,
    source: 'OG Capital Markets Use Cases — Trading / Brokering',
    status: 'PLANNED' as const,
  },
  {
    id: 'FLOW-008',
    name: 'Corporate Actions',
    category: 'Post-Trade',
    description: 'On-chain corporate actions processing. Dividends, interest payments, redemptions, voting.',
    stepCount: 0,
    source: 'OG Capital Markets Use Cases — Asset Services',
    status: 'PLANNED' as const,
  },
  {
    id: 'FLOW-009',
    name: 'Tokenized MMF',
    category: 'Investing',
    description: 'Tokenized money market fund creation, distribution, NAV pricing, subscription/redemption, yield distribution.',
    stepCount: 0,
    source: 'OG Capital Markets Use Cases — MMF Workflow',
    status: 'PLANNED' as const,
  },
  {
    id: 'FLOW-010',
    name: 'ETF Creation / Redemption',
    category: 'Investing',
    description: 'Tokenized ETF basket creation, AP workflow, in-kind transfers, NAV arbitrage.',
    stepCount: 0,
    source: 'OG Capital Markets Use Cases — ETF Workflow',
    status: 'PLANNED' as const,
  }
];

export const cantonFlowSteps: CantonFlowStep[] = [
  {
    flowId: 'FLOW-001',
    step: 1,
    templateName: 'Custody Role',
    action: 'Hold underlying securities at CSD/custodian',
    inputs: 'Securities (UST, Gilts, EU Govt Bonds)',
    outputs: 'Custodied asset record',
    triggersNext: 'Issuer Role',
    cantonPrivacy: 'Private — custody positions not visible to counterparties',
    notes: 'DTCC DTC (US), Euroclear EUI (UK), BNY',
  },
  {
    flowId: 'FLOW-001',
    step: 2,
    templateName: 'Tokenize / Issuer Role',
    action: 'Tokenize custodied securities on Canton',
    inputs: 'Custodied asset record',
    outputs: 'On-chain tokenized security',
    triggersNext: 'Exchange Role',
    cantonPrivacy: 'Private — token creation visible only to issuer + custodian',
    notes: 'DTCC ComposerX, Archax tokenisation engine',
  },
  {
    flowId: 'FLOW-001',
    step: 3,
    templateName: 'Exchange Role',
    action: 'Execute repo trade — match borrower and lender',
    inputs: 'Tokenized security + cash leg availability',
    outputs: 'Matched trade (terms, haircut, rate, tenor)',
    triggersNext: 'Settlement Rail',
    cantonPrivacy: 'Private — trade terms visible only to counterparties',
    notes: 'Tradeweb execution platform',
  },
  {
    flowId: 'FLOW-001',
    step: 4,
    templateName: 'Settlement Rail',
    action: 'Provide cash leg — stablecoin or tokenized deposit',
    inputs: 'Cash requirement from matched trade',
    outputs: 'On-chain cash (USDC, DiSH, SBC, USDM1)',
    triggersNext: 'Settlement Rail (DvP)',
    cantonPrivacy: 'Private — cash balances not visible to other parties',
    notes: 'Circle USDC (R1-R2), LSEG DiSH (R3-R4), Brale SBC (R2), M1X USDM1 (R2)',
  },
  {
    flowId: 'FLOW-001',
    step: 5,
    templateName: 'Settlement Rail',
    action: 'Atomic DvP settlement — simultaneous swap of collateral and cash',
    inputs: 'Tokenized security + on-chain cash',
    outputs: 'Collateral transferred, cash transferred',
    triggersNext: 'Collateral Agent',
    cantonPrivacy: 'Private — settlement visible only to counterparties',
    notes: 'Canton atomic settlement — T+0, 24/7',
  },
  {
    flowId: 'FLOW-001',
    step: 6,
    templateName: 'Collateral Agent',
    action: 'Manage collateral lifecycle — apply haircuts, enable reuse/rehypothecation',
    inputs: 'Settled collateral position',
    outputs: 'Collateral available for reuse in next transaction',
    triggersNext: 'Oracle / Pricing',
    cantonPrivacy: 'Private — reuse chain visible only to relevant parties in each leg',
    notes: 'First collateral reuse demonstrated Round 2 (Dec 2025)',
  },
  {
    flowId: 'FLOW-001',
    step: 7,
    templateName: 'Oracle / Pricing',
    action: 'Mark-to-market collateral, trigger margin call if value drops',
    inputs: 'Market prices, collateral positions',
    outputs: 'Updated valuation; margin call if triggered',
    triggersNext: 'Settlement Rail (margin)',
    cantonPrivacy: 'Private — valuations calculated per-counterparty',
    notes: 'Chainlink, Kaiko, S&P Global',
  },
  {
    flowId: 'FLOW-001',
    step: 8,
    templateName: 'Settlement Rail',
    action: 'Unwind repo — reverse DvP at maturity, return securities and cash + interest',
    inputs: 'Repo terms, maturity trigger',
    outputs: 'Securities returned to lender, cash + interest returned to borrower',
    triggersNext: 'Custody Role (cycle complete)',
    cantonPrivacy: 'Private — unwind visible only to counterparties',
    notes: 'Intraday = same-day unwind. 24/7 availability.',
  },
  {
    flowId: 'FLOW-002',
    step: 1,
    templateName: 'Liquidity Provider',
    action: 'Enter bilateral OTC derivative trade between counterparties',
    inputs: 'Trade terms (ISDA Master Agreement)',
    outputs: 'Executed derivative contract on-chain',
    triggersNext: 'Compliance Check',
    cantonPrivacy: 'Private — trade terms between two counterparties only',
    notes: 'Cumberland, B2C2, FalconX, GSR, Flowdesk, QCP',
  },
  {
    flowId: 'FLOW-002',
    step: 2,
    templateName: 'Compliance Check',
    action: 'Validate counterparty eligibility, verify ISDA CSA terms encoded in smart contract',
    inputs: 'Counterparty identity, ISDA CSA parameters',
    outputs: 'Validated trade, margin requirements (IM + VM schedule)',
    triggersNext: 'Oracle / Pricing',
    cantonPrivacy: 'Private — compliance data per-counterparty',
    notes: 'ISDA CSA IM/VM requirements encoded as smart contract logic',
  },
  {
    flowId: 'FLOW-002',
    step: 3,
    templateName: 'Oracle / Pricing',
    action: 'Calculate initial margin (IM) and variation margin (VM) requirement',
    inputs: 'Market data, portfolio exposure, CSA schedule',
    outputs: 'Margin call amount (IM and/or VM)',
    triggersNext: 'Custody Role',
    cantonPrivacy: 'Private — margin calculations per-counterparty pair',
    notes: 'Real-time 24/7 margin cycle — no T+1 delay',
  },
  {
    flowId: 'FLOW-002',
    step: 4,
    templateName: 'Custody Role',
    action: 'Pledge collateral from custody to meet margin call',
    inputs: 'Margin call amount, available collateral in custody',
    outputs: 'Collateral pledged on-chain to counterparty',
    triggersNext: 'Collateral Agent',
    cantonPrivacy: 'Private — pledge visible only to pledgor + pledgee',
    notes: 'Novel collateral types: yield-bearing stablecoins, tokenized MMFs',
  },
  {
    flowId: 'FLOW-002',
    step: 5,
    templateName: 'Collateral Agent',
    action: 'Manage pledged collateral, enforce CSA terms automatically, handle substitutions',
    inputs: 'Pledged collateral, CSA smart contract rules',
    outputs: 'Collateral held per CSA terms, automated enforcement',
    triggersNext: 'Oracle / Pricing (loop back to Step 3)',
    cantonPrivacy: 'Private — collateral terms per bilateral agreement',
    notes: 'Continuous loop: pricing → margin → pledge → manage → reprice',
  },
  {
    flowId: 'FLOW-002',
    step: 6,
    templateName: 'Settlement Rail',
    action: 'Settle margin payments on demand — any time, any day',
    inputs: 'Margin call from pricing oracle',
    outputs: 'Cash or collateral transferred between counterparties',
    triggersNext: 'Collateral Agent (update position)',
    cantonPrivacy: 'Private — settlement per-counterparty',
    notes: '24/7 margining — no batch windows, instant settlement',
  },
  {
    flowId: 'FLOW-003',
    step: 1,
    templateName: 'Tokenize / Issuer Role',
    action: 'Structure and create tokenized security — deploy smart contract with asset terms',
    inputs: 'Asset terms, legal structure, offering documents',
    outputs: 'Token smart contract deployed on Canton',
    triggersNext: 'Registry Role',
    cantonPrivacy: 'Private — issuance terms between issuer + legal advisors',
    notes: 'BNP NeoBonds, GS DAP, HSBC Orion, Archax, Fairmint, Ondo',
  },
  {
    flowId: 'FLOW-003',
    step: 2,
    templateName: 'Registry Role',
    action: 'Register token as legal security, create ownership record on-chain',
    inputs: 'Deployed token contract',
    outputs: 'Registered security with legal record of ownership',
    triggersNext: 'Compliance Check',
    cantonPrivacy: 'Private — registry visible to issuer + regulator',
    notes: 'DTCC, Euroclear, Nasdaq, Broadridge',
  },
  {
    flowId: 'FLOW-003',
    step: 3,
    templateName: 'Compliance Check',
    action: 'Screen and verify investors — KYC/AML checks before allocation',
    inputs: 'Investor identity documents',
    outputs: 'Verified investor status (pass/fail)',
    triggersNext: 'Identity Provider',
    cantonPrivacy: 'Private — compliance per-investor',
    notes: 'TRM Labs, Elliptic, Chainalysis, Lukka',
  },
  {
    flowId: 'FLOW-003',
    step: 4,
    templateName: 'Identity Provider',
    action: 'Issue on-chain verifiable credential for verified investor',
    inputs: 'Verified investor from compliance check',
    outputs: 'On-chain verifiable credential (VC)',
    triggersNext: 'Exchange Role',
    cantonPrivacy: 'Private — credential held by investor, verified on demand',
    notes: 'C7 Identity, Quadrata, Veriff',
  },
  {
    flowId: 'FLOW-003',
    step: 5,
    templateName: 'Exchange Role',
    action: 'Distribute tokens — primary market sale or book-building',
    inputs: 'Registered token + pool of verified investors',
    outputs: 'Token allocations to investors',
    triggersNext: 'Settlement Rail',
    cantonPrivacy: 'Private — allocations between issuer + each investor',
    notes: 'Tradeweb, Coinbase, Kraken, or direct distribution',
  },
  {
    flowId: 'FLOW-003',
    step: 6,
    templateName: 'Settlement Rail',
    action: 'DvP settlement of primary allocation — tokens vs cash atomically',
    inputs: 'Token allocation + investor cash',
    outputs: 'Tokens delivered to investor, cash to issuer',
    triggersNext: 'Custody Role',
    cantonPrivacy: 'Private — settlement per-investor',
    notes: 'Atomic DvP on Canton — simultaneous exchange',
  },
  {
    flowId: 'FLOW-003',
    step: 7,
    templateName: 'Custody Role',
    action: 'Safekeep tokens for investors post-settlement',
    inputs: 'Settled tokens',
    outputs: 'Tokens held in custody, available for secondary trading or collateral use',
    triggersNext: 'Flow complete (feeds into secondary trading, collateral flows)',
    cantonPrivacy: 'Private — custody per-holder',
    notes: 'Fireblocks, Copper, BitGo, BNY, Taurus, Anchorage',
  },
  {
    flowId: 'FLOW-004',
    step: 1,
    templateName: 'Custody Role',
    action: 'Hold securities in local jurisdiction CSD',
    inputs: 'Securities held at domestic CSD',
    outputs: 'Custodied position (e.g. Gilts at Euroclear EUI, USTs at DTCC DTC)',
    triggersNext: 'Issuer Role',
    cantonPrivacy: 'Private — domestic custody positions per-holder',
    notes: 'Euroclear EUI (UK Gilts), DTCC DTC (US Treasuries)',
  },
  {
    flowId: 'FLOW-004',
    step: 2,
    templateName: 'Tokenize / Issuer Role',
    action: 'Tokenize domestically custodied securities on Canton',
    inputs: 'Custodied position at local CSD',
    outputs: 'On-chain tokenized asset representing underlying',
    triggersNext: 'Exchange Role',
    cantonPrivacy: 'Private — tokenization visible to CSD + custodian',
    notes: 'Archax (Gilts), DTCC ComposerX (USTs)',
  },
  {
    flowId: 'FLOW-004',
    step: 3,
    templateName: 'Exchange Role',
    action: 'Match cross-border financing — domestic collateral vs foreign cash',
    inputs: 'Tokenized asset (Jurisdiction A) + cash need (Jurisdiction B)',
    outputs: 'Matched cross-border repo trade',
    triggersNext: 'Settlement Rail (cash)',
    cantonPrivacy: 'Private — trade between counterparties only',
    notes: 'Tradeweb cross-border execution',
  },
  {
    flowId: 'FLOW-004',
    step: 4,
    templateName: 'Settlement Rail',
    action: 'Provide cross-currency cash leg — tokenized deposits in target currency',
    inputs: 'Cash requirement in foreign currency',
    outputs: 'Tokenized deposit in target currency (GBP, EUR, USD)',
    triggersNext: 'Settlement Rail (DvP)',
    cantonPrivacy: 'Private — cash balances per-counterparty',
    notes: 'LSEG DiSH multi-currency tokenized commercial bank deposits',
  },
  {
    flowId: 'FLOW-004',
    step: 5,
    templateName: 'Settlement Rail',
    action: 'Atomic cross-border DvP — collateral from CSD A settles vs cash in currency B',
    inputs: 'Tokenized security + cross-currency tokenized deposit',
    outputs: 'Collateral transferred across borders atomically',
    triggersNext: 'Collateral Agent',
    cantonPrivacy: 'Private — cross-border settlement per-counterparty',
    notes: 'First achieved Canton Round 3 (Jan 2026). Round 4 added Gilts.',
  },
  {
    flowId: 'FLOW-004',
    step: 6,
    templateName: 'Collateral Agent',
    action: 'Manage cross-border collateral with haircuts, repo interest, and maturity terms encoded in smart contract',
    inputs: 'Cross-border collateral position',
    outputs: 'Managed position with embedded terms, auto-enforcement',
    triggersNext: 'Oracle / Pricing (loop for mark-to-market)',
    cantonPrivacy: 'Private — terms per bilateral agreement',
    notes: 'TreasurySpring validated haircuts + interest in smart contracts (R3-R4)',
  }
];

export const templateParticipants: TemplateParticipantMapping[] = [
  { templateName: 'Custody Role', participantId: 'p_archax', organization: 'Archax', isSV: false, isValidator: true, cantonRole: 'Custody, Exchange, Tokenized Assets', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Custody Role', participantId: 'p_wellsfargo', organization: 'Wells Fargo', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Repo, Payment' },
  { templateName: 'Custody Role', participantId: 'p_citi', organization: 'Citi', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Repo, Liquidity, Payment' },
  { templateName: 'Custody Role', participantId: 'p_morganstanley', organization: 'Morgan Stanley', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Repo, Liquidity' },
  { templateName: 'Custody Role', participantId: 'p_taurus', organization: 'Taurus', isSV: true, isValidator: true, cantonRole: 'Custody, Tokenization, Trading, Settlement, Governance' },
  { templateName: 'Custody Role', participantId: 'p_lloyds', organization: 'Lloyds Banking Group', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Cash Lender, Infrastructure' },
  { templateName: 'Custody Role', participantId: 'p_mpch', organization: 'MPCH', isSV: true, isValidator: false, cantonRole: 'Super Validator, Custody', foundationCategory: 'NaaS' },
  { templateName: 'Custody Role', participantId: 'p_hydrax', organization: 'HydraX', isSV: false, isValidator: true, cantonRole: 'Infrastructure', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Custody Role', participantId: 'p_copper', organization: 'Copper', isSV: true, isValidator: true, cantonRole: 'Custody', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Custody Role', participantId: 'p_bnymellon', organization: 'BNY Mellon', isSV: false, isValidator: false, cantonRole: 'Custody' },
  { templateName: 'Custody Role', participantId: 'p_bny', organization: 'BNY', isSV: false, isValidator: false, cantonRole: 'Custody' },
  { templateName: 'Custody Role', participantId: 'p_bitgo', organization: 'BitGo', isSV: true, isValidator: true, cantonRole: 'Custody', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Custody Role', participantId: 'p_finoa', organization: 'Finoa', isSV: false, isValidator: true, cantonRole: 'Custody', foundationCategory: 'NaaS' },
  { templateName: 'Custody Role', participantId: 'p_hextrust', organization: 'Hex Trust', isSV: true, isValidator: true, cantonRole: 'Custody' },
  { templateName: 'Custody Role', participantId: 'p_bnp', organization: 'BNP Paribas', isSV: false, isValidator: false, cantonRole: 'Tokenized Assets', foundationCategory: 'Tokenization' },
  { templateName: 'Custody Role', participantId: 'p_cygnet', organization: 'Cygnet', isSV: false, isValidator: true, cantonRole: 'Custody' },
  { templateName: 'Custody Role', participantId: 'p_db', organization: 'Deutsche Bank', isSV: false, isValidator: false, cantonRole: 'Financing' },
  { templateName: 'Custody Role', participantId: 'p_fireblocks', organization: 'Fireblocks', isSV: true, isValidator: true, cantonRole: 'Custody Tech' },
  { templateName: 'Custody Role', participantId: 'p_hsbc', organization: 'HSBC', isSV: false, isValidator: false, cantonRole: 'Tokenized Assets', foundationCategory: 'Tokenization' },
  { templateName: 'Custody Role', participantId: 'p_sc', organization: 'Standard Chartered', isSV: false, isValidator: false, cantonRole: 'Custody' },
  { templateName: 'Custody Role', participantId: 'p_zodiacustody', organization: 'Zodia Custody', isSV: true, isValidator: true, cantonRole: 'Custody', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Custody Role', participantId: 'p_anchorage', organization: 'Anchorage Digital', isSV: false, isValidator: true, cantonRole: 'Custody' },
  { templateName: 'Custody Role', participantId: 'p_galaxy', organization: 'Galaxy', isSV: false, isValidator: true, cantonRole: 'Liquidity' },
  { templateName: 'Settlement Rail', participantId: 'p_asterizmprotocol', organization: 'Asterizm Protocol', isSV: false, isValidator: false, cantonRole: 'Infrastructure', foundationCategory: 'Bridges/Oracles' },
  { templateName: 'Settlement Rail', participantId: 'p_wellsfargo', organization: 'Wells Fargo', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Repo, Payment' },
  { templateName: 'Settlement Rail', participantId: 'p_citi', organization: 'Citi', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Repo, Liquidity, Payment' },
  { templateName: 'Settlement Rail', participantId: 'p_morganstanley', organization: 'Morgan Stanley', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Repo, Liquidity' },
  { templateName: 'Settlement Rail', participantId: 'p_socgen', organization: 'Societe Generale', isSV: false, isValidator: false, cantonRole: 'Settlement, Issuer, Repo, Collateral' },
  { templateName: 'Settlement Rail', participantId: 'p_lseg', organization: 'LSEG', isSV: false, isValidator: false, cantonRole: 'Exchange, Settlement, Payment, Infrastructure' },
  { templateName: 'Settlement Rail', participantId: 'p_kinexys_jpm', organization: 'Kinexys by J.P. Morgan', isSV: false, isValidator: false, cantonRole: 'Settlement, Payment, Deposit Token' },
  { templateName: 'Settlement Rail', participantId: 'p_taurus', organization: 'Taurus', isSV: true, isValidator: true, cantonRole: 'Custody, Tokenization, Trading, Settlement, Governance' },
  { templateName: 'Settlement Rail', participantId: 'p_talos', organization: 'Talos', isSV: true, isValidator: true, cantonRole: 'Trading Infrastructure, Data Intelligence, Settlement' },
  { templateName: 'Settlement Rail', participantId: 'p_lloyds', organization: 'Lloyds Banking Group', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Cash Lender, Infrastructure' },
  { templateName: 'Settlement Rail', participantId: 'p_broadridge', organization: 'Broadridge', isSV: true, isValidator: true, cantonRole: 'Repo Financing', foundationCategory: 'Tokenization' },
  { templateName: 'Settlement Rail', participantId: 'p_paxos', organization: 'Paxos', isSV: false, isValidator: true, cantonRole: 'Stablecoin Issuer' },
  { templateName: 'Settlement Rail', participantId: 'p_circleusdcx', organization: 'Circle USDCx', isSV: true, isValidator: true, cantonRole: 'Stablecoin Issuer', foundationCategory: 'Bridges/Oracles' },
  { templateName: 'Settlement Rail', participantId: 'p_denex', organization: 'Denex', isSV: false, isValidator: false, cantonRole: 'Infrastructure' },
  { templateName: 'Settlement Rail', participantId: 'p_dtcc', organization: 'DTCC', isSV: true, isValidator: true, cantonRole: 'Registry + Issuer', foundationCategory: 'Tokenization' },
  { templateName: 'Settlement Rail', participantId: 'p_euroclear', organization: 'Euroclear', isSV: false, isValidator: false, cantonRole: 'Registry + Collateral' },
  { templateName: 'Settlement Rail', participantId: 'p_hydrax', organization: 'HydraX', isSV: false, isValidator: true, cantonRole: 'Infrastructure', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Settlement Rail', participantId: 'p_hifi', organization: 'HIFI', isSV: false, isValidator: true, cantonRole: 'Payment, Settlement, Stablecoin' },
  { templateName: 'Settlement Rail', participantId: 'p_hkex', organization: 'HKEX Synapse', isSV: false, isValidator: false, cantonRole: 'Exchange', foundationCategory: 'Tokenization' },
  { templateName: 'Settlement Rail', participantId: 'p_silvana', organization: 'Silvana', isSV: false, isValidator: true, cantonRole: 'Orderbook, DEX, ZKP Analytics', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Settlement Rail', participantId: 'p_zodiacustody', organization: 'Zodia Custody', isSV: true, isValidator: true, cantonRole: 'Custody', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Settlement Rail', participantId: 'p_zerohash', organization: 'Zero Hash', isSV: true, isValidator: true, cantonRole: 'Settlement' },
  { templateName: 'Settlement Rail', participantId: 'p_versana', organization: 'Versana', isSV: false, isValidator: false, cantonRole: 'Syndicated Loans', foundationCategory: 'Tokenization' },
  { templateName: 'Settlement Rail', participantId: 'p_hiddenroad', organization: 'Hidden Road', isSV: false, isValidator: false, cantonRole: 'Prime Brokerage, Settlement' },
  { templateName: 'Settlement Rail', participantId: 'p_brale', organization: 'Brale', isSV: false, isValidator: true, cantonRole: 'Stablecoins, Wallets, Payments', foundationCategory: 'DeFi' },
  { templateName: 'Settlement Rail', participantId: 'p_franklin', organization: 'Temple Digital Group', isSV: false, isValidator: true, cantonRole: 'Trading Platform, CLOB, Settlement', foundationCategory: 'DeFi' },
  { templateName: 'Settlement Rail', participantId: 'p_ubyx', organization: 'Ubyx', isSV: true, isValidator: true, cantonRole: 'Settlement' },
  { templateName: 'Settlement Rail', participantId: 'p_mesh', organization: 'Mesh', isSV: true, isValidator: true, cantonRole: 'Payments, Stablecoin Settlement' },
  { templateName: 'Settlement Rail', participantId: 'p_monstera', organization: 'Monstera', isSV: true, isValidator: true, cantonRole: 'Onboarding, Infrastructure, SV' },
  { templateName: 'Settlement Rail', participantId: 'p_wlfi', organization: 'World Liberty Financial', isSV: false, isValidator: false, cantonRole: 'Stablecoin Issuer, Payment' },
  { templateName: 'Settlement Rail', participantId: 'p_bitwave', organization: 'Bitwave', isSV: true, isValidator: true, cantonRole: 'Stablecoins, Compliance, Financing', foundationCategory: 'Data & Analytics' },
  { templateName: 'Settlement Rail', participantId: 'p_bosphorussv', organization: 'Bosphorus SV', isSV: true, isValidator: true, cantonRole: 'Regional Distribution, Stablecoins, RWA' },
  { templateName: 'Settlement Rail', participantId: 'p_sendwallet', organization: 'Send', isSV: false, isValidator: false, cantonRole: 'Wallet, DEX, Stablecoin, Staking', foundationCategory: 'DeFi' },
  { templateName: 'Settlement Rail', participantId: 'p_usdt0tether', organization: 'USDT0 Tether', isSV: true, isValidator: true, cantonRole: 'Stablecoins' },
  { templateName: 'Settlement Rail', participantId: 'p_m1xglobal', organization: 'M1X Global', isSV: false, isValidator: false, cantonRole: 'Stablecoin, Liquidity', foundationCategory: 'DeFi' },
  { templateName: 'Settlement Rail', participantId: 'p_handipay', organization: 'HandiPay', isSV: false, isValidator: false, cantonRole: 'Payment, Wallet' },
  { templateName: 'Settlement Rail', participantId: 'p_cantara', organization: 'Cantara', isSV: false, isValidator: false, cantonRole: 'Payment Platform', foundationCategory: 'DeFi' },
  { templateName: 'Settlement Rail', participantId: 'p_lilizverigift', organization: 'LILIZ (Verigift)', isSV: false, isValidator: true, cantonRole: 'Fundraising, Charity, Social Impact' },
  { templateName: 'Registry Role', participantId: 'p_asterizmprotocol', organization: 'Asterizm Protocol', isSV: false, isValidator: false, cantonRole: 'Infrastructure', foundationCategory: 'Bridges/Oracles' },
  { templateName: 'Registry Role', participantId: 'p_broadridge', organization: 'Broadridge', isSV: true, isValidator: true, cantonRole: 'Repo Financing', foundationCategory: 'Tokenization' },
  { templateName: 'Registry Role', participantId: 'p_denex', organization: 'Denex', isSV: false, isValidator: false, cantonRole: 'Infrastructure' },
  { templateName: 'Registry Role', participantId: 'p_digitalasset', organization: 'Digital Asset', isSV: true, isValidator: true, cantonRole: 'Orchestration', foundationCategory: 'Daml Dev Solutions' },
  { templateName: 'Registry Role', participantId: 'p_dtcc', organization: 'DTCC', isSV: true, isValidator: true, cantonRole: 'Registry + Issuer', foundationCategory: 'Tokenization' },
  { templateName: 'Registry Role', participantId: 'p_euroclear', organization: 'Euroclear', isSV: false, isValidator: false, cantonRole: 'Registry + Collateral' },
  { templateName: 'Registry Role', participantId: 'p_fairmint', organization: 'Fairmint', isSV: false, isValidator: true, cantonRole: 'Tokenized Assets', foundationCategory: 'Tokenization' },
  { templateName: 'Registry Role', participantId: 'p_hydrax', organization: 'HydraX', isSV: false, isValidator: true, cantonRole: 'Infrastructure', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Registry Role', participantId: 'p_euronext', organization: 'Euronext', isSV: false, isValidator: false, cantonRole: 'Exchange, Registry, Infrastructure' },
  { templateName: 'Registry Role', participantId: 'p_nasdaq', organization: 'Nasdaq', isSV: true, isValidator: true, cantonRole: 'Exchange + Tech' },
  { templateName: 'Registry Role', participantId: 'p_versana', organization: 'Versana', isSV: false, isValidator: false, cantonRole: 'Syndicated Loans', foundationCategory: 'Tokenization' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_archax', organization: 'Archax', isSV: false, isValidator: true, cantonRole: 'Custody, Exchange, Tokenized Assets', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_socgen', organization: 'Societe Generale', isSV: false, isValidator: false, cantonRole: 'Settlement, Issuer, Repo, Collateral' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_wlfi', organization: 'World Liberty Financial', isSV: false, isValidator: false, cantonRole: 'Stablecoin Issuer, Payment' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_goldmansachs', organization: 'Goldman Sachs', isSV: false, isValidator: false, cantonRole: 'Issuer, Infrastructure', foundationCategory: 'Tokenization' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_zenith', organization: 'Zenith', isSV: true, isValidator: true, cantonRole: 'Virtual Blockchains, EVM Compatibility, ZK Settlement' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_woodsideai', organization: 'Woodside AI', isSV: true, isValidator: true, cantonRole: 'Private Credit, Fund Admin, AI, Onboarding' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_taurus', organization: 'Taurus', isSV: true, isValidator: true, cantonRole: 'Custody, Tokenization, Trading, Settlement, Governance' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_realt', organization: 'RealT', isSV: false, isValidator: false, cantonRole: 'Tokenized Assets' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_securitize', organization: 'Securitize', isSV: false, isValidator: false, cantonRole: 'Tokenized Assets' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_ondofinance', organization: 'Ondo Finance', isSV: false, isValidator: false, cantonRole: 'Tokenized Assets' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_fairmint', organization: 'Fairmint', isSV: false, isValidator: true, cantonRole: 'Tokenized Assets', foundationCategory: 'Tokenization' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_excellar', organization: 'Excellar', isSV: false, isValidator: false, cantonRole: 'Tokenized Assets' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_circleusdcx', organization: 'Circle USDCx', isSV: true, isValidator: true, cantonRole: 'Stablecoin Issuer', foundationCategory: 'Bridges/Oracles' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_blackrock', organization: 'BlackRock', isSV: false, isValidator: false, cantonRole: 'Asset Manager' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_blackmantacapital', organization: 'Black Manta Capital', isSV: false, isValidator: false, cantonRole: 'Tokenized Assets', foundationCategory: 'Tokenization' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_bitsafecbtc', organization: 'BitSafe CBTC', isSV: false, isValidator: false, cantonRole: 'Collateral, Compliance, Tokenized Assets', foundationCategory: 'DeFi' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_paxos', organization: 'Paxos', isSV: false, isValidator: true, cantonRole: 'Stablecoin Issuer' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_21shares', organization: '21shares', isSV: false, isValidator: true, cantonRole: 'ETP Issuer' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_trize', organization: 'T-RIZE', isSV: false, isValidator: true, cantonRole: 'Issuer', foundationCategory: 'Tokenization' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_hashnoteusyc', organization: 'Hashnote USYC', isSV: false, isValidator: false, cantonRole: 'Issuer', foundationCategory: 'Tokenization' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_coinshares', organization: 'CoinShares', isSV: false, isValidator: true, cantonRole: 'Issuer' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_trakx', organization: 'Trakx', isSV: false, isValidator: false, cantonRole: 'Index Provider', foundationCategory: 'DeFi' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_novaprime', organization: 'Novaprime', isSV: false, isValidator: false, cantonRole: 'Loan Processing', foundationCategory: 'Tokenization' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_21shares', organization: '21.co / 21Shares', isSV: false, isValidator: true, cantonRole: 'Issuer' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_sg', organization: 'Société Générale', isSV: false, isValidator: true, cantonRole: 'Tokenized Assets', foundationCategory: 'Tokenization' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_republic', organization: 'Republic', isSV: true, isValidator: true, cantonRole: 'Issuer, Wallet', foundationCategory: 'NaaS' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_hsbc', organization: 'HSBC', isSV: false, isValidator: false, cantonRole: 'Tokenized Assets', foundationCategory: 'Tokenization' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_bosphorussv', organization: 'Bosphorus SV', isSV: true, isValidator: true, cantonRole: 'Regional Distribution, Stablecoins, RWA' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_eleox', organization: 'Eleox', isSV: false, isValidator: false, cantonRole: 'Commodity Tokenization', foundationCategory: 'Tokenization' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_bnp', organization: 'BNP Paribas', isSV: false, isValidator: false, cantonRole: 'Tokenized Assets', foundationCategory: 'Tokenization' },
  { templateName: 'Tokenize / Issuer Role', participantId: 'p_franklin', organization: 'Temple Digital Group', isSV: false, isValidator: true, cantonRole: 'Trading Platform, CLOB, Settlement', foundationCategory: 'DeFi' },
  { templateName: 'Exchange Role', participantId: 'p_archax', organization: 'Archax', isSV: false, isValidator: true, cantonRole: 'Custody, Exchange, Tokenized Assets', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Exchange Role', participantId: 'p_euronext', organization: 'Euronext', isSV: false, isValidator: false, cantonRole: 'Exchange, Registry, Infrastructure' },
  { templateName: 'Exchange Role', participantId: 'p_lseg', organization: 'LSEG', isSV: false, isValidator: false, cantonRole: 'Exchange, Settlement, Payment, Infrastructure' },
  { templateName: 'Exchange Role', participantId: 'p_21shares', organization: '21shares', isSV: false, isValidator: true, cantonRole: 'ETP Issuer' },
  { templateName: 'Exchange Role', participantId: 'p_talos', organization: 'Talos', isSV: true, isValidator: true, cantonRole: 'Trading Infrastructure, Data Intelligence, Settlement' },
  { templateName: 'Exchange Role', participantId: 'p_taurus', organization: 'Taurus', isSV: true, isValidator: true, cantonRole: 'Custody, Tokenization, Trading, Settlement, Governance' },
  { templateName: 'Exchange Role', participantId: 'p_tradeweb', organization: 'Tradeweb', isSV: true, isValidator: true, cantonRole: 'Exchange', foundationCategory: 'Tokenization' },
  { templateName: 'Exchange Role', participantId: 'p_cantex', organization: 'Cantex', isSV: false, isValidator: false, cantonRole: 'Exchange', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Exchange Role', participantId: 'p_bybit', organization: 'ByBit', isSV: false, isValidator: true, cantonRole: 'Exchange', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Exchange Role', participantId: 'p_gate', organization: 'Gate', isSV: false, isValidator: false, cantonRole: 'Exchange', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Exchange Role', participantId: 'p_kucoin', organization: 'KuCoin', isSV: false, isValidator: true, cantonRole: 'Exchange', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Exchange Role', participantId: 'p_mexc', organization: 'MEXC', isSV: false, isValidator: true, cantonRole: 'Exchange', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Exchange Role', participantId: 'p_tradefast', organization: 'Trade.Fast', isSV: false, isValidator: false, cantonRole: 'Exchange', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Exchange Role', participantId: 'p_kraken', organization: 'Kraken', isSV: false, isValidator: true, cantonRole: 'Exchanges' },
  { templateName: 'Exchange Role', participantId: 'p_nasdaq', organization: 'Nasdaq', isSV: true, isValidator: true, cantonRole: 'Exchange + Tech' },
  { templateName: 'Exchange Role', participantId: 'p_franklin', organization: 'Temple Digital Group', isSV: false, isValidator: true, cantonRole: 'Trading Platform, CLOB, Settlement', foundationCategory: 'DeFi' },
  { templateName: 'Exchange Role', participantId: 'p_coinbase', organization: 'Coinbase', isSV: false, isValidator: false, cantonRole: 'Exchanges' },
  { templateName: 'Exchange Role', participantId: 'p_silvana', organization: 'Silvana', isSV: false, isValidator: true, cantonRole: 'Orderbook, DEX, ZKP Analytics', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Exchange Role', participantId: 'p_binance', organization: 'Binance', isSV: false, isValidator: false, cantonRole: 'Exchanges' },
  { templateName: 'Exchange Role', participantId: 'p_hkex', organization: 'HKEX Synapse', isSV: false, isValidator: false, cantonRole: 'Exchange', foundationCategory: 'Tokenization' },
  { templateName: 'Compliance Check', participantId: 'p_bitsafecbtc', organization: 'BitSafe CBTC', isSV: false, isValidator: false, cantonRole: 'Collateral, Compliance, Tokenized Assets', foundationCategory: 'DeFi' },
  { templateName: 'Compliance Check', participantId: 'p_hypernative', organization: 'Hypernative', isSV: true, isValidator: true, cantonRole: 'Compliance' },
  { templateName: 'Compliance Check', participantId: 'p_mica', organization: 'MiCa', isSV: false, isValidator: false, cantonRole: 'Compliance' },
  { templateName: 'Compliance Check', participantId: 'p_quantstamp', organization: 'Quantstamp', isSV: true, isValidator: true, cantonRole: 'Compliance' },
  { templateName: 'Compliance Check', participantId: 'p_svnodeopslimited', organization: 'SV-Nodeops-Limited', isSV: true, isValidator: true, cantonRole: 'Governance' },
  { templateName: 'Compliance Check', participantId: 'p_memora', organization: 'Memora', isSV: false, isValidator: false, cantonRole: 'Infrastructure', foundationCategory: 'Data & Analytics' },
  { templateName: 'Compliance Check', participantId: 'p_registerlabs', organization: 'Register Labs', isSV: false, isValidator: false, cantonRole: 'Compliance', foundationCategory: 'Data & Analytics' },
  { templateName: 'Compliance Check', participantId: 'p_akascan', organization: 'AKASCAN', isSV: false, isValidator: false, cantonRole: 'Compliance' },
  { templateName: 'Compliance Check', participantId: 'p_bitalpha', organization: 'Bitalpha', isSV: false, isValidator: false, cantonRole: 'Compliance' },
  { templateName: 'Compliance Check', participantId: 'p_bitwave', organization: 'Bitwave', isSV: true, isValidator: true, cantonRole: 'Stablecoins, Compliance, Financing', foundationCategory: 'Data & Analytics' },
  { templateName: 'Compliance Check', participantId: 'p_coinmetrics', organization: 'Coin Metrics', isSV: true, isValidator: true, cantonRole: 'Data', foundationCategory: 'Data & Analytics' },
  { templateName: 'Compliance Check', participantId: 'p_elliptic', organization: 'Elliptic', isSV: true, isValidator: true, cantonRole: 'Compliance', foundationCategory: 'Data & Analytics' },
  { templateName: 'Compliance Check', participantId: 'p_lukka', organization: 'Lukka', isSV: true, isValidator: true, cantonRole: 'Compliance', foundationCategory: 'Data & Analytics' },
  { templateName: 'Compliance Check', participantId: 'p_trm', organization: 'TRM', isSV: true, isValidator: true, cantonRole: 'Compliance', foundationCategory: 'Data & Analytics' },
  { templateName: 'Wallet Provider', participantId: 'p_bitgo', organization: 'BitGo', isSV: true, isValidator: true, cantonRole: 'Custody', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_copper', organization: 'Copper', isSV: true, isValidator: true, cantonRole: 'Custody', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_hydrax', organization: 'HydraX', isSV: false, isValidator: true, cantonRole: 'Infrastructure', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_mpch', organization: 'MPCH', isSV: true, isValidator: false, cantonRole: 'Super Validator, Custody', foundationCategory: 'NaaS' },
  { templateName: 'Wallet Provider', participantId: 'p_taurus', organization: 'Taurus', isSV: true, isValidator: true, cantonRole: 'Custody, Tokenization, Trading, Settlement, Governance' },
  { templateName: 'Wallet Provider', participantId: 'p_consolewallet', organization: 'Console Wallet', isSV: false, isValidator: false, cantonRole: 'Wallet', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_c8wallet', organization: 'C8 Wallet', isSV: false, isValidator: false, cantonRole: 'Wallet', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_valawalletfinoa', organization: 'Vala Wallet Finoa', isSV: false, isValidator: true, cantonRole: 'Wallet' },
  { templateName: 'Wallet Provider', participantId: 'p_handipay', organization: 'HandiPay', isSV: false, isValidator: false, cantonRole: 'Payment, Wallet' },
  { templateName: 'Wallet Provider', participantId: 'p_fivenorth', organization: 'Five North', isSV: true, isValidator: true, cantonRole: 'Wallet', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_nightly', organization: 'Nightly', isSV: false, isValidator: false, cantonRole: 'Wallet', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_zorowallet', organization: 'Zoro Wallet', isSV: false, isValidator: false, cantonRole: 'Wallet', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_ledger', organization: 'Ledger', isSV: true, isValidator: true, cantonRole: 'Wallet', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_safe', organization: 'Safe', isSV: false, isValidator: false, cantonRole: 'Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_sendwallet', organization: 'Send', isSV: false, isValidator: false, cantonRole: 'Wallet, DEX, Stablecoin, Staking', foundationCategory: 'DeFi' },
  { templateName: 'Wallet Provider', participantId: 'p_fireblocks', organization: 'Fireblocks', isSV: true, isValidator: true, cantonRole: 'Custody Tech' },
  { templateName: 'Wallet Provider', participantId: 'p_zodiacustody', organization: 'Zodia Custody', isSV: true, isValidator: true, cantonRole: 'Custody', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_cansaitenkai', organization: 'Cansai Tenkai', isSV: false, isValidator: true, cantonRole: 'Wallet, NaaS', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_dfns', organization: 'Dfns', isSV: true, isValidator: true, cantonRole: 'Wallets', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_cypherock', organization: 'Cypherock', isSV: false, isValidator: false, cantonRole: 'Wallets', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_bronfoundation', organization: 'Bron Foundation', isSV: false, isValidator: false, cantonRole: 'Wallets', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_brale', organization: 'Brale', isSV: false, isValidator: true, cantonRole: 'Stablecoins, Wallets, Payments', foundationCategory: 'DeFi' },
  { templateName: 'Wallet Provider', participantId: 'p_blockdaemon', organization: 'Blockdaemon', isSV: true, isValidator: true, cantonRole: 'Infrastructure', foundationCategory: 'NaaS' },
  { templateName: 'Wallet Provider', participantId: 'p_1pilot', organization: '1Pilot', isSV: false, isValidator: false, cantonRole: 'Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_metamask', organization: 'MetaMask', isSV: false, isValidator: false, cantonRole: 'Wallets' },
  { templateName: 'Wallet Provider', participantId: 'p_republic', organization: 'Republic', isSV: true, isValidator: true, cantonRole: 'Issuer, Wallet', foundationCategory: 'NaaS' },
  { templateName: 'Liquidity Provider', participantId: 'p_citadel', organization: 'Citadel Securities', isSV: false, isValidator: true, cantonRole: 'Liquidity' },
  { templateName: 'Liquidity Provider', participantId: 'p_citi', organization: 'Citi', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Repo, Liquidity, Payment' },
  { templateName: 'Liquidity Provider', participantId: 'p_morganstanley', organization: 'Morgan Stanley', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Repo, Liquidity' },
  { templateName: 'Liquidity Provider', participantId: 'p_talos', organization: 'Talos', isSV: true, isValidator: true, cantonRole: 'Trading Infrastructure, Data Intelligence, Settlement' },
  { templateName: 'Liquidity Provider', participantId: 'p_cumberland', organization: 'Cumberland', isSV: true, isValidator: true, cantonRole: 'Liquidity', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Liquidity Provider', participantId: 'p_drw', organization: 'DRW', isSV: false, isValidator: false, cantonRole: 'Liquidity' },
  { templateName: 'Liquidity Provider', participantId: 'p_yzilabs', organization: 'YZi Labs', isSV: true, isValidator: true, cantonRole: 'Investor, Ecosystem Development, SV, Governance' },
  { templateName: 'Liquidity Provider', participantId: 'p_coinshares', organization: 'CoinShares', isSV: false, isValidator: true, cantonRole: 'Issuer' },
  { templateName: 'Liquidity Provider', participantId: 'p_treasuryspring', organization: 'TreasurySpring', isSV: false, isValidator: false, cantonRole: 'Repo Platform, Liquidity' },
  { templateName: 'Liquidity Provider', participantId: 'p_virtu', organization: 'Virtu Financial', isSV: false, isValidator: false, cantonRole: 'Market Maker' },
  { templateName: 'Liquidity Provider', participantId: 'p_optiver', organization: 'Optiver', isSV: false, isValidator: false, cantonRole: 'Market Maker' },
  { templateName: 'Liquidity Provider', participantId: 'p_imc', organization: 'IMC', isSV: false, isValidator: false, cantonRole: 'Market Maker' },
  { templateName: 'Liquidity Provider', participantId: 'p_b2c2', organization: 'B2C2', isSV: false, isValidator: true, cantonRole: 'Liquidity' },
  { templateName: 'Liquidity Provider', participantId: 'p_flowdesk', organization: 'Flowdesk', isSV: false, isValidator: false, cantonRole: 'Liquidity Provider, Market Maker' },
  { templateName: 'Liquidity Provider', participantId: 'p_gsr', organization: 'GSR', isSV: false, isValidator: true, cantonRole: 'Liquidity' },
  { templateName: 'Liquidity Provider', participantId: 'p_gemini', organization: 'Gemini', isSV: false, isValidator: false, cantonRole: 'Liquidity' },
  { templateName: 'Liquidity Provider', participantId: 'p_galaxy', organization: 'Galaxy', isSV: false, isValidator: true, cantonRole: 'Liquidity' },
  { templateName: 'Liquidity Provider', participantId: 'p_flowtraders', organization: 'Flow Traders', isSV: false, isValidator: true, cantonRole: 'Liquidity' },
  { templateName: 'Liquidity Provider', participantId: 'p_falconx', organization: 'FalconX', isSV: false, isValidator: true, cantonRole: 'Prime Broker' },
  { templateName: 'Liquidity Provider', participantId: 'p_cantonswap', organization: 'Tradecraft', isSV: false, isValidator: false, cantonRole: 'DEX', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Liquidity Provider', participantId: 'p_wintermute', organization: 'Wintermute', isSV: false, isValidator: true, cantonRole: 'Liquidity' },
  { templateName: 'Liquidity Provider', participantId: 'p_qcp', organization: 'QCP', isSV: false, isValidator: false, cantonRole: 'Liquidity Provider, Market Maker' },
  { templateName: 'Liquidity Provider', participantId: 'p_yuce', organization: 'YUCE', isSV: false, isValidator: true, cantonRole: 'Prediction Markets, Risk Pricing' },
  { templateName: 'Collateral Agent', participantId: 'p_bny', organization: 'BNY', isSV: false, isValidator: false, cantonRole: 'Custody' },
  { templateName: 'Collateral Agent', participantId: 'p_broadridge', organization: 'Broadridge', isSV: true, isValidator: true, cantonRole: 'Repo Financing', foundationCategory: 'Tokenization' },
  { templateName: 'Collateral Agent', participantId: 'p_copper', organization: 'Copper', isSV: true, isValidator: true, cantonRole: 'Custody', foundationCategory: 'Custodians & Wallets' },
  { templateName: 'Collateral Agent', participantId: 'p_euroclear', organization: 'Euroclear', isSV: false, isValidator: false, cantonRole: 'Registry + Collateral' },
  { templateName: 'Collateral Agent', participantId: 'p_taurus', organization: 'Taurus', isSV: true, isValidator: true, cantonRole: 'Custody, Tokenization, Trading, Settlement, Governance' },
  { templateName: 'Collateral Agent', participantId: 'p_morganstanley', organization: 'Morgan Stanley', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Repo, Liquidity' },
  { templateName: 'Collateral Agent', participantId: 'p_citi', organization: 'Citi', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Repo, Liquidity, Payment' },
  { templateName: 'Collateral Agent', participantId: 'p_wellsfargo', organization: 'Wells Fargo', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Repo, Payment' },
  { templateName: 'Collateral Agent', participantId: 'p_lloyds', organization: 'Lloyds Banking Group', isSV: false, isValidator: false, cantonRole: 'Custody, Settlement, Collateral, Cash Lender, Infrastructure' },
  { templateName: 'Collateral Agent', participantId: 'p_equilend', organization: 'EquiLend', isSV: false, isValidator: false, cantonRole: 'Securities Finance', foundationCategory: 'Tokenization' },
  { templateName: 'Oracle / Pricing', participantId: 'p_spglobal', organization: 'S&P Global', isSV: false, isValidator: false, cantonRole: 'Data + Infrastructure' },
  { templateName: 'Oracle / Pricing', participantId: 'p_redstone', organization: 'Redstone', isSV: false, isValidator: false, cantonRole: 'Oracle', foundationCategory: 'Bridges/Oracles' },
  { templateName: 'Oracle / Pricing', participantId: 'p_chainlink', organization: 'Chainlink', isSV: true, isValidator: true, cantonRole: 'Oracle', foundationCategory: 'Bridges/Oracles' },
  { templateName: 'Oracle / Pricing', participantId: 'p_coinmetrics', organization: 'Coin Metrics', isSV: true, isValidator: true, cantonRole: 'Data', foundationCategory: 'Data & Analytics' },
  { templateName: 'Oracle / Pricing', participantId: 'p_kaiko', organization: 'Kaiko', isSV: true, isValidator: true, cantonRole: 'Data', foundationCategory: 'Bridges/Oracles' },
  { templateName: 'Oracle / Pricing', participantId: 'p_pyth', organization: 'Pyth Network', isSV: false, isValidator: true, cantonRole: 'Oracle' },
  { templateName: 'Oracle / Pricing', participantId: 'p_woodsideai', organization: 'Woodside AI', isSV: true, isValidator: true, cantonRole: 'Private Credit, Fund Admin, AI, Onboarding' },
  { templateName: 'Oracle / Pricing', participantId: 'p_talos', organization: 'Talos', isSV: true, isValidator: true, cantonRole: 'Trading Infrastructure, Data Intelligence, Settlement' },
  { templateName: 'Oracle / Pricing', participantId: 'p_proofgroup', organization: 'Proof Group', isSV: true, isValidator: true, cantonRole: 'NaaS, Data & Analytics, Governance' },
  { templateName: 'Oracle / Pricing', participantId: 'p_thetie', organization: 'The Tie', isSV: false, isValidator: false, cantonRole: 'Data Provider', foundationCategory: 'Data & Analytics' },
  { templateName: 'Oracle / Pricing', participantId: 'p_alumlabs', organization: 'ALUM Labs', isSV: false, isValidator: false, cantonRole: 'Onchain Data', foundationCategory: 'Data & Analytics' },
  { templateName: 'Oracle / Pricing', participantId: 'p_chainalysis', organization: 'Chainalysis', isSV: false, isValidator: false, cantonRole: 'Onchain Data' },
  { templateName: 'Oracle / Pricing', participantId: 'p_chatatechnologies', organization: 'Chata Technologies', isSV: false, isValidator: false, cantonRole: 'Onchain Data', foundationCategory: 'Data & Analytics' },
  { templateName: 'Oracle / Pricing', participantId: 'p_noves', organization: 'Noves', isSV: false, isValidator: false, cantonRole: 'Onchain Data', foundationCategory: 'Data & Analytics' },
  { templateName: 'Oracle / Pricing', participantId: 'p_roundbeat', organization: 'RoundBeat', isSV: false, isValidator: true, cantonRole: 'Monitoring, NaaS, Data & Analytics' },
  { templateName: 'Oracle / Pricing', participantId: 'p_silvana', organization: 'Silvana', isSV: false, isValidator: true, cantonRole: 'Orderbook, DEX, ZKP Analytics', foundationCategory: 'Trading & Exchanges' },
  { templateName: 'Oracle / Pricing', participantId: 'p_yuce', organization: 'YUCE', isSV: false, isValidator: true, cantonRole: 'Prediction Markets, Risk Pricing' },
  { templateName: 'Identity Provider', participantId: 'p_7ridgec7', organization: '7RIDGE C7', isSV: true, isValidator: true, cantonRole: 'Governance, Identity', foundationCategory: 'NaaS' },
  { templateName: 'Identity Provider', participantId: 'p_quadrata', organization: 'Quadrata', isSV: false, isValidator: false, cantonRole: 'Identity', foundationCategory: 'NaaS' },
  { templateName: 'Identity Provider', participantId: 'p_veriff', organization: 'Veriff', isSV: false, isValidator: false, cantonRole: 'Identity' },
  { templateName: 'Explorer', participantId: 'p_ccexplorer', organization: 'CC Explorer', isSV: false, isValidator: false, cantonRole: 'Explorer', foundationCategory: 'Blockchain Explorers' },
  { templateName: 'Explorer', participantId: 'p_ccview', organization: 'CC View', isSV: false, isValidator: false, cantonRole: 'Explorer', foundationCategory: 'Blockchain Explorers' },
  { templateName: 'Explorer', participantId: 'p_sekoyalabs', organization: 'Sekoya Labs', isSV: false, isValidator: false, cantonRole: 'Node Operator, Analytics', foundationCategory: 'NaaS' },
  { templateName: 'Explorer', participantId: 'p_thetie', organization: 'The Tie', isSV: false, isValidator: false, cantonRole: 'Data Provider', foundationCategory: 'Data & Analytics' },
  { templateName: 'Explorer', participantId: 'p_5nlighthouse', organization: '5N Lighthouse', isSV: false, isValidator: false, cantonRole: 'Explorer', foundationCategory: 'Blockchain Explorers' },
  { templateName: 'Explorer', participantId: 'p_flowryd', organization: 'Flowryd', isSV: false, isValidator: true, cantonRole: 'Orchestration', foundationCategory: 'Data & Analytics' },
  { templateName: 'Bridge Role', participantId: 'p_bitsafecbtc', organization: 'BitSafe CBTC', isSV: false, isValidator: false, cantonRole: 'Collateral, Compliance, Tokenized Assets', foundationCategory: 'DeFi' },
  { templateName: 'Bridge Role', participantId: 'p_circleusdcx', organization: 'Circle USDCx', isSV: true, isValidator: true, cantonRole: 'Stablecoin Issuer', foundationCategory: 'Bridges/Oracles' },
  { templateName: 'Bridge Role', participantId: 'p_mesh', organization: 'Mesh', isSV: true, isValidator: true, cantonRole: 'Payments, Stablecoin Settlement' },
  { templateName: 'Bridge Role', participantId: 'p_zenith', organization: 'Zenith', isSV: true, isValidator: true, cantonRole: 'Virtual Blockchains, EVM Compatibility, ZK Settlement' },
  { templateName: 'Bridge Role', participantId: 'p_layerzero', organization: 'LayerZero', isSV: true, isValidator: true, cantonRole: 'Bridge', foundationCategory: 'Bridges/Oracles' },
  { templateName: 'Bridge Role', participantId: 'p_wormhole', organization: 'Wormhole', isSV: true, isValidator: true, cantonRole: 'Bridge' },
  { templateName: 'Bridge Role', participantId: 'p_bosphorussv', organization: 'Bosphorus SV', isSV: true, isValidator: true, cantonRole: 'Regional Distribution, Stablecoins, RWA' },
  { templateName: 'Bridge Role', participantId: 'p_chainlink', organization: 'Chainlink', isSV: true, isValidator: true, cantonRole: 'Oracle', foundationCategory: 'Bridges/Oracles' },
  { templateName: 'Bridge Role', participantId: 'p_usdt0tether', organization: 'USDT0 Tether', isSV: true, isValidator: true, cantonRole: 'Stablecoins' }
];

// ── Lookup Helpers ──────────────────────────────────────

export function getTemplateByName(name: string): CantonTemplate | undefined {
  return cantonTemplates.find(t => t.name === name);
}

export function getFlowById(id: string): CantonFlow | undefined {
  return cantonFlows.find(f => f.id === id);
}

export function getStepsForFlow(flowId: string): CantonFlowStep[] {
  return cantonFlowSteps.filter(s => s.flowId === flowId).sort((a, b) => a.step - b.step);
}

export function getParticipantsForTemplate(templateName: string): TemplateParticipantMapping[] {
  return templateParticipants.filter(tp => tp.templateName === templateName);
}

export function getTemplatesForParticipant(participantId: string): string[] {
  return [...new Set(
    templateParticipants
      .filter(tp => tp.participantId === participantId)
      .map(tp => tp.templateName)
  )];
}
