import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ExportColumn {
  key: string;
  label: string;
  width?: number;
}

export interface PDFExportOptions {
  title: string;
  columns: ExportColumn[];
  orientation?: 'portrait' | 'landscape';
}

/**
 * Escapes CSV values to handle commas, quotes, and newlines
 */
function escapeCSVValue(value: unknown): string {
  if (value === null || value === undefined) {
    return '';
  }
  
  const stringValue = String(value);
  
  // If the value contains comma, quote, or newline, wrap in quotes and escape internal quotes
  if (stringValue.includes(',') || stringValue.includes('"') || stringValue.includes('\n')) {
    return `"${stringValue.replace(/"/g, '""')}"`;
  }
  
  return stringValue;
}

/**
 * Exports data to CSV format and triggers browser download
 */
export function exportToCSV(
  data: Record<string, unknown>[],
  filename: string,
  columns?: ExportColumn[]
): void {
  if (!data || data.length === 0) {
    console.warn('No data to export');
    return;
  }

  // If columns not provided, auto-detect from first data item
  const exportColumns = columns || Object.keys(data[0]).map(key => ({
    key,
    label: key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1')
  }));

  // Create CSV header
  const headers = exportColumns.map(col => escapeCSVValue(col.label));
  const csvContent = [headers.join(',')];

  // Add data rows
  data.forEach(row => {
    const values = exportColumns.map(col => escapeCSVValue(row[col.key]));
    csvContent.push(values.join(','));
  });

  // Create and trigger download
  const csvString = csvContent.join('\n');
  const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', filename.endsWith('.csv') ? filename : `${filename}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

/**
 * Exports data to PDF format and triggers browser download
 */
export function exportToPDF(
  data: Record<string, unknown>[],
  filename: string,
  options: PDFExportOptions
): void {
  if (!data || data.length === 0) {
    console.warn('No data to export');
    return;
  }

  const { title, columns, orientation = 'portrait' } = options;
  
  // Create new PDF document
  const doc = new jsPDF({
    orientation,
    unit: 'mm',
    format: 'a4'
  });

  // Add header with title and timestamp
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 20);
  
  // Add Flowryd branding
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Flowryd', 14, 28);
  
  // Add timestamp
  const timestamp = new Date().toLocaleString();
  doc.text(`Generated on: ${timestamp}`, 14, 34);

  // Prepare table data
  const tableColumns = columns.map(col => col.label);
  const tableRows = data.map(row => 
    columns.map(col => {
      const value = row[col.key];
      return value === null || value === undefined ? '' : String(value);
    })
  );

  // Add table using autoTable
  autoTable(doc, {
    head: [tableColumns],
    body: tableRows,
    startY: 45,
    styles: {
      fontSize: 8,
      cellPadding: 2,
    },
    headStyles: {
      fillColor: [39, 39, 42], // zinc-800
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [250, 250, 250], // Very light gray
    },
    columnStyles: columns.reduce((acc, col, index) => {
      if (col.width) {
        acc[index] = { cellWidth: col.width };
      }
      return acc;
    }, {} as Record<number, { cellWidth: number }>),
    margin: { top: 45, right: 14, bottom: 20, left: 14 },
  });

  // Save the PDF
  const pdfFilename = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
  doc.save(pdfFilename);
}

/**
 * Formats a date for display in exports
 */
export function formatDateForExport(date: Date | string | null | undefined): string {
  if (!date) return '';
  
  try {
    const dateObj = typeof date === 'string' ? new Date(date) : date;
    return dateObj.toLocaleDateString();
  } catch {
    return String(date);
  }
}

/**
 * Formats a number for display in exports
 */
export function formatNumberForExport(num: number | null | undefined): string {
  if (num === null || num === undefined) return '';
  return num.toLocaleString();
}